# Midterm 2020

In [1]:
lender_rates = {'Fannie Mae': .05, 'Bank of America': .065, 'Quicken Loans': .045}
prime_interest_rate = .04
amount_above_prime = [lender_rates[x] - prime_interest_rate for x in lender_rates.keys()]
loan_amounts = [100000, 150000, 200000, 500000]
interest_due = [x * prime_interest_rate for x in loan_amounts]
prime_mortgages = [x <= 200000 and x > 100000 for x in loan_amounts]
prime_mortgages2 = [x for x in loan_amounts if x <= 200000 and x > 100000]
shoe_string = 'adidas_ultra_boost'

In [38]:
lowercase_letters = 'abcdefghijklmnopqrstuvwxyz'
uppercase_letters = lowercase_letters.upper()
letters = lowercase_letters + uppercase_letters
digits = '0123456789'
address = '5500 Campanile Drive'
missing_stuff = '5500  '
vowels = 'aeiou'
word = 'facetious'
Y = [x for x in letters if x < 'd' or x > 'j']
W = [x for x in letters if x == 'd' or x == 'j' or x < 'q']
Z = [x > 'd' and x < 'j' for x in letters]
R = [x for x in word if x in vowels]
#. This is a dictionary comprehension.  Look at how it works
vowel2index = {v:i for (i, v) in enumerate(vowels)}
index2vowel = {v:k for (k,v) in vowel2index.items()}

# Exercises

# A

Define a consonant to be any character in `letters` that is not in `vowels`.  Construct a single Python expression that returns a string consisting of the consonants in `word`.
Note: you will not receive credit for simply writing an expression that **lists** the answer.  For example.

```
'fcts'
```

A full-credit solution must compute the answer using `vowels`, `letters` and `word`.

# B

Determine what values of x the following test is true for:

```
vowels[x] == index2vowel[x]
```

Write a loop that contains the following expression in the body 

```
print(x, vowels[x] == index2vowel[x])
```

and loops through all values of `x` for which it is `True`.  It should print `x`
and `True` for each value of `x` that makes `vowels[x] == index2vowel[x]` `True`.

# C

Write some code that returns a string consisting of the characters that are both in `digits` and in `address`.  

# D

Write some code that returns a string consisting of the letters that are either in `uppercase_letters` or in `address`.

# E

Write a function called `find_digits` that will take any string and return a **string** containing the digits  and spaces in that string.  For the digits use  `digits` (defined above)  After writing the function, apply it to `address` (as defined above).  The answer should be

```
'5500  '
```

Then apply the function to `address` again and test whether the function returns a value `==` to `missing_stuff`.  The result should be as follows:

```
>>> find_digits(address) == missing_stuff
True
```

Then apply the function to `digits` and test whether the function returns a value `==` to `digits`.   Show that result to prove your function does the right thing.


# F

Modify `find_digits` as defined in problem  **E** so that its argument is optional and it behaves as follows:

```
>>> find_digits() == find_digits('radish')
True
>>> find_digits() == find_digits('fumigate')
True
```

Note:  All the previously discussed examples using `find_digits` should continue to behave as before.  Also, there are many answers to this problem.  Try to keep things simple.

# F 

Now write a function `remove_char` that has two arguments, `inp` and `char`, an
input string and a character; `remove_char` returns an exact copy of `inp`
except that all instances of `char` have been removed.   If `char` does not
occur in `inp`, it should return `inp` unchanged

It should behave as follows:

```
>>> remove_char(vowels, 'a')
'eiou'
>>> remove_char(vowels, 'o')
'aeiu'
>>> remove_char(vowels, 'o') == 'aeio'
True
>>> remove_char('beep', 'a') == 'beep'
True
>>> remove_char('infinitive', 'q')
'infinitive'
```



# G

Now **modify** `remove_char` from problem F so that it ignores
case but does everything it did before.

It should behave as follows:

```
>>> remove_char(vowels, 'A')
'eiou'
>>> remove_char('AEIOU', 'o')
'AEIU'
>>> remove_char('AeiOU', 'o')
'AeiU'
>>> remove_char(vowels, 'a')
'eiou'
>>> remove_char('AEIOU', 'O')
'AEIU'
>>> remove_char(vowels, 'o') == 'aeiu'
True
>>> remove_char('Mississippi', 'I')
'Msssspp'
```


# H

Consider `vowel2index`.  It is a mapping from vowels to integers.  Write amn expression that returns the integer associated with `"b"` in `vowel2index`.  Note:  This question has a **very** simple answer.  It is about
whether you understand what type of data structure `vowel2index` is, and how you use it.

# I

Write a simple one-line Python expression that operates on `vowels` and returns 

```
'axexixoxu'
```

# J


Write a Python expression which operates on `consonants` and returns the following value

```
'gh'
```

# K

Write a Python expression which operates on `Z` and returns the following value

```
[False, False, False]
```

# L

Write a Python expression which operates on `W` and returns the following value

```
['p','A']
```

##       Part Two

Write functions that behave according to the descriptions given.

# 1

Write a function (`tweeners`) that takes two lowercse letters as arguments and returns the
string consisting of all the letters in the alphabet between them (in alphabetical order)

```
>>> tweeners('a','c')
'b'
>>> tweeners('m',  'r')
'nopq'
>>> tweeners('m',  'n')
''
```

If the letters passed in are not in alphabetical order, `tweeners` should return the empty string:

```
>>> tweeners('c',  'a')
''
```

Hint:  This has a really simply answer.  Think list comprehension.  Think filtering.

# 2

Write a function called `nonoverlap`
which takes four letters as arguments.   Call them `first`, `second`,`third`
and `fourth`; `nonoverlap` should first find the string consisting of all the 
letters in the alphabet between them `first` and `second`.  Call those letters `fs`,

It should call the function `tweeners` (defined in the last problem)
to do this.  Note: **No credit for a solution that ignores this instruction**.   

The function `nonoverlap` should
also call `tweeners` on `third` and `fourth`.   Call the result of that
`tf`; `nonoverlap` should then return a string consisting of the letters which are 
are in either `fs` or `tf` but are not in both.
It doesn't matter what order they're in.

Some examples

```
>>> print(tweeners('a','e'))
bcd
>>> print(tweeners('c','g'))
def
>>> print(nonoverlap('a','e','m','r'))
bcdnopq
>>> print(nonoverlap('a','e','c','g'))
bcef
>>> print(nonoverlap('c','g','a','e'))
bcef
>>> print(nonoverlap('e','a','c','g'))
def
```

Finally,  the last two arguments of `nonoverlap` should be
optional. 

```
>>> nonoverlap('e','a')
''
>>> nonoverlap('e','a','c')
''
```

## Part 4

In [41]:
employees = ['happy', 'sleepy', 'dopey', 'bashful', 'grumpy', 'doc', 'sneezy']
employeeEmail = {'happy': ['sleepy','dopey'], 'dopey':['dopey'],'doc': employees,
                 'sleepy': ['bashful','doc', 'happy'],'grumpy':[],
                 'bashful': ['dopey']}
#employeeEmail[1] = ['norman']
secret_word = 'utilitarian'
flip = {'0':'1', '1':'0'}
bit_string = '001110'
flipped = [flip[x] for x in bit_string]

# 1

Write an expression which operates on `employees` and returns

```
['doc', 'sneezy']
```

# 2

Write an expression which operates on `employees` and returns

```
'pp'
```

# 3

Write an expression which operates on `employeeEmail` and returns

```
"shf"
```

# 4

Write an expression which operates on `secret_word` and returns

```
'uiiain'
```

Part 5

In [44]:
import numpy as np
x = np.array([5,13,23,47,9])
y = np.ones((5,))
w = np.ones((2,5))
z = w + x

# a

Write out an expression which return the shape of `z`,

# b

Write out an expression which operates on `z` and returns

```
array([ 6., 14., 24., 48., 10.])
```

# c

Write out an expression that returns an array containing the elementwise sum of the elements in `w` and `z`.

# d

Consider:

In [47]:
x + z

Explain why you get the result that you get for `x + z`. 

# e

Note the following:

In [48]:
x < 20

array([ True,  True, False, False,  True])

The result above is called a **Boolean array** because it only contains instances of the
type `bool` (`True` and `False`). Such Boolean arrays can be used to index arrays (basically
if they are of the same length).  Using a Boolean array this way is called using a **Boolean mask**.

# e (ctd.)

Using a Boolean mask, write an expression that returns an array containing the **members** of `x` that are less than `20`.

# f

Now consider

In [49]:
two_d_array = np.array([[1,2],[2,1],[5,5],[9,4]])
two_d_array

array([[1, 2],
       [2, 1],
       [5, 5],
       [9, 4]])

Write an expression that returns the third row of `two_d_array`.

Write an expression that returns `two_d_array` omitting the first column.

Write an expression that returns the following subarray of `two_d_array`.

```
array([[2, 1],
       [5, 5]])
```