# Midterm study Notebook

The problems in Part One are taken from a previous quiz.  Write the value of each expression in the space provided. A helpful reminder.  When applied to strings, '<' checks alphabetical order.  So

```
>>> 'a' < 'b'
True
>>> 'b' < 'a'
False
>>> 'a' < 'a'
False
```

When applied to strings '+' does concatenation:

```
>>> 'a' + 'x'
'ax'
```


## Part One

In [2]:
lender_rates = {'Fannie Mae': .05, 'Bank of America': .065, 'Quicken Loans': .045}
prime_interest_rate = .04
amount_above_prime = [lender_rates[x] - prime_interest_rate for x in lender_rates.keys()]
loan_amounts = [100000, 150000, 200000, 500000]
interest_due = [x * prime_interest_rate for x in loan_amounts]
prime_mortgages = [x <= 200000 and x > 100000 for x in loan_amounts]
prime_mortgages2 = [x for x in loan_amounts if x <= 200000 and x > 100000]
shoe_string = 'adidas_ultra_boost'

In [3]:
(lender_rates, prime_interest_rate, amount_above_prime, 
 loan_amounts, interest_due, prime_mortgages)

({'Fannie Mae': 0.05, 'Bank of America': 0.065, 'Quicken Loans': 0.045},
 0.04,
 [0.010000000000000002, 0.025, 0.0049999999999999975],
 [100000, 150000, 200000, 500000],
 [4000.0, 6000.0, 8000.0, 20000.0],
 [False, True, True, False])

In [4]:
letters = 'abcdefghijklmnopqrstuvwxyz'
vowels = 'aeiou'
word = 'facetious'
X = [l for l in letters if l not in vowels]
Y = [x for x in letters if x > 'd' and x < 'j']
W = [x for x in letters if x == 'd' or x == 'j' or x < 'q']
Z = [x > 'd' and x < 'j' for x in letters]
R = [x for x in word if x in vowels]
consonants = [l for l in letters if l not in vowels]
#. This is a dictionary comprehension.  Look at how it works
consonant2vowel = {consonants[i]:v for (i, v) in enumerate(vowels)}
vowel2consonant = {v:k for (k,v) in consonant2vowel.items()}

# Exercises

# A

Write some code to turn `X` into a string. Remember `X` was created by a list comprehension, so it is initially defined to be a list.  The string you should get is:

```
'bcdfghjklmnpqrstvwxyz'
```

In [5]:
''.join(X)

'bcdfghjklmnpqrstvwxyz'

# B

Write some code to produce a list of letters that are in `letters` but are not in `Y`.  Your code should use the current values of `letters` and `Y` and it should be a list comprehension using a filter.  Your result should look like this:

```
['a', 'b', 'c', 'd', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
```

In [6]:
[l for l in letters if l not in Y]

['a',
 'b',
 'c',
 'd',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

# C

Write some code that returns a string consisting of the letters that are both in `W` and in `Y`.  

In [7]:
[l for l in W if l in Y]

['e', 'f', 'g', 'h', 'i']

# D

Write a function called `find_vowels` that will take any string and return a **string** containing the vowels in that string.  For the vowels use  `vowels` (defined above)  After writing the function, apply it to `word` (as defined above).  The answer should be

```
'aeiou'
```

Then apply the function to `word` again and test whether the function returns a value `==` to `vowels`.
The result you get should be:

```
>>> find_vowels(word) == vowels
True
```

Then apply the function to `'radish'`.  The answer should be:

```
'ai'
```



In [8]:
def find_vowels (inp = vowels):
    return ''.join([l for l in inp if l in vowels])

In [12]:
find_vowels(word)

'aeiou'

In [11]:
find_vowels ('radish')

'ai'

In [10]:
find_vowels(word) == vowels

True

# E

Modify `find_vowels` as defined in problem  **D** so that its argument is optional and it behaves as follows:

```
>>> find_vowels() == vowels
True
```

Note:  All the previously discussed examples using `find_vowels` should continue to behave as before.

In [13]:
find_vowels() == vowels

True

# F 

Now write a function `same_chars` that
determines if two strings have exactly the same
set of characters.  It should behave as follows:

```
>>> same_chars(vowels, 'aeiou')
True
>>> same_chars(vowels, 'eioua')
True
>>> same_chars(vowels, 'uoiea')
True
>>> same_chars(vowels, 'eiou')
False
>>> same_chars('bcd','dcb')
True
>>> if same_chars('xyz','zyx'):
...     print('Same!`)
... else:
        print('Different')
Same!
```

Hint: Use sets. Remember how easy it is in Python to turn one type into another:

```
>>> list('abc')
['a', 'b', 'c']
```


In [14]:
def same_chars (word1,word2):
    return set(word1)  == set(word2)

In [15]:
same_chars('bcd','dcb')

True

In [17]:
same_chars(vowels, 'uoiea')

True

In [18]:
same_chars(vowels, 'uoie')

False

In [21]:
if same_chars('xyz','zyx'):
    print('Same!')
else:
    print('Different!')

Same!


# G

Consider `R`. Remember `R` filters the elements of `word` with the condition `x in vowels`.

Write some code that performs a test to show that `vowels` (a string) contains the same 
characters as `R` (a list).

In [22]:
same_chars(vowels,R)

True

# H

Consider `consonant2vowel`.  It is a mapping from consonants to vowels.  Write some code that returns the vowel associated with `"b"` in `consonant2vowel`.  Note:  This question has a **very** simple answer.  It is about
whether you understand what type of dsata structure `consonant2vowel` is, and holw you use it.

In [23]:
consonant2vowel['b']

'a'

# I

Write a simple one-line Python expression that operates on `vowels` and returns 

```
['ba', 'be','bi', 'bo','bu']
```

In [24]:
['b' + x for x in vowels]

['ba', 'be', 'bi', 'bo', 'bu']

# J

Look at `interest_due`.  Using that as a model, write a simple expression that returns a list containing
the result of dividing every loan amount in `loan_amounts` by 100,000.


In [27]:
[x/10**6 for x in loan_amounts]

# OK to write it out
#[x/100000 for x in loan_amounts]

[0.1, 0.15, 0.2, 0.5]

# K

Write a simple one line Python expression that operates on X and returns

```
['b', 'c']
```


In [28]:
X[:2]

['b', 'c']

# L


Write a Python expression which operates on `letters` and returns the following value

```
'ghi'
```

In [31]:
 letters[6:9]

'ghi'

# M

Write a Python expression which operates on `Z` and returns the following value

```
[False, False, False]
```

In [33]:
Z[:3]

[False, False, False]

# N

Write a Python expression which operates on `Y` and returns the following value:

```
['e','i']
```

In [35]:
[l for l in Y if l in vowels]

['e', 'i']

# O

Write a line of code which operates on `Y` and returns `False`.

# P

Write a line of code which returns the following value when applied to `vowels`:

```
[True, True, False, False, False]
```

# Q

Write a line of code which operates on `consonant2vowel` and returns the following value.

```
'e'
```



Write a line of code which operates on `vowel2consonant` and returns the following value.

```
'g'
```

##       Part Two

Write functions that behave according to the descriptions given.

# 1

Write a function that takes two numbers as arguments and multiplies them together and adds 1 to the result.  Call your function `product_successor`.  Then:

```
>>> product_successor(3,2)
7.0
>>> product_successor(5,9)
46.0
```

# 2

Write a function called `product_successor_ratios`
which takes four numbers as arguments.   Call them `a`,`b`,`c`' and `d`;
`product_successor_ratios` should first find the product succesor of `a` and `b`.

That is, it should multiply `a` and `b` together
and add one to the result.  It should call the function `product_successor` (defined in the last problem))
to do this.  Note: **No credit for a solution that ignores this instruction**.   

`product_successor_ratios` should
also call `product_successor` on `c` and `d` (multiplying `c` and `d` together and adding 1 to the result).
It should return the ratio obtained by dividing the product successor of `a` and `b` 
by the product successor of `c` and `d`.

Note: It took a lot of English to say this but the body of the `product_successor_ratios`
function is essentially one line of code.  Here are some examples illustratinmg its behavior:

```
>>> product_successor_ratios(3,2,5,9)
0.15217391304347827
>>> product_successor_ratios(5,9,3,2)
6.571428571428571
>>> product_successor_ratios(3,2,5,9) + product_successor_ratios(5,9,3,2)
6.72360248447205
>>> product_successor_ratios(5,9,3,0)
46.0
>>> product_successor_ratios(5,9,0,0)
46.0

```


Finally,  the last two arguments of `product_successor_ratio` should be
optional.  Here are the results when they are omitted.

```
>>> print(product_successor_ratio(5,9,1))
23.0
>>> print(product_successor_ratio(5,9))
23.0
```

## Part 3

Reminders: `range(n)` returns a list of the integers from 0 up to but not including `n`.

```
>>> range(10)
[0,1,2,3,4,5,6,7,8,9]
```

`'str0'.join(str_seq)`  returns a string gotten by joining together the elements of `str_seq` with `str0`. It is the opposite of `split`.  It is an error if the elements of `str_seq` are not all strings:

```
>>> ''.join(['a','b','c'])
'abc'
>>> 'x'.join(['a','b','c'])
'axbxc'
>>> 'x'.join([1,2,3])
TypeError      
...
TypeError: sequence item 0: expected string, int found
>>> 'i'.join(['m','ss','ss','pp',''])
'mississippi'
>>> 'i'.join(['m','ss','ss','pp'])
'mississipp'
```




In [72]:
letters = ('a', 'b', 'c', 'd', 'e', 'f', 'g', 
           'h', 'i', 'j', 'k', 'l', 'm', 'n', 
           'o', 'p', 'q', 'r', 's', 't', 'u', 
           'v', 'w', 'x', 'y', 'z')
vowels = 'aeiou'
digits = list(range(4))
word_list = ['beap','pine', 'bake', 'isle']
weird_list = [word_list[x][x] for x in digits]
word3 = ''.join([x[1] for x in word_list])
word4 = 'x'.join(['o','o','o',''])
char_list = [x for x in word4 if x in vowels]
word1 = 'rambunctious'
word2 = 'mellifluous'
WW = word1 + word2
Z = [x for x in WW if x in 'lmn']
favorite_words = {'Noam Chomsky': word2, 'Leonard Bloomfield': word1, 'John Rupert Firth': word3}

# a

Write out an expression which applies to `word3` and returns

```
'rambunctious'
```

# b

Find a value for `L` (a list)  for which the following piece of code produces the result shown.  There are some helpful examples above.

```
>>> 'i'.join(L)
'mississippi'
```

# c

What is the Python type of `digits` (as defined above)?

# d

What is the Python type of `digits[0]`?

# e

Find a value for `word_list2` (a list) which makes the code below have the given value
(see the example using `weird_list` and `word_list` above).

```
>>> [word_list2[x][x] for x in digits]
['v ','o','t','e']
```


# f

Write an expression which returns the **set** of vowels in  `char_list`.

# g 

Write an expression which operates on `favorite_word` and returns:

```
'ias'
```

# h

Write an expression which operates on `favorite_word` and returns:

```
'bun'
```

Hint: Use a splice.  Remember that `favorite_word` is a dictionary. Values are retrieved from a dictionary by keys, and therefore it makes no sense to use numerical indices (or splices) directly on a dictionary.  But you might be able to use a splice on something inside the dictionary.

# i

Write an expression which retrieves

```
['a','b','c','x','y''z']
```

from `letters`.  Hint: use a list comprehension with a filtering condition.

## Part 4

In [73]:
employees = ['happy', 'sleepy', 'dopey', 'bashful', 'grumpy', 'doc', 'sneezy']
employeeEmail = {'happy': ['sleepy','dopey'], 'dopey':['dopey'],'doc': employees,
                 'sleepy': ['bashful','doc', 'happy'],'grumpy':[],
                 'bashful': ['dopey']}
#employeeEmail[1] = ['norman']
secret_word = 'utilitarian'
flip = {'0':'1', '1':'0'}
bit_string = '001110'
flipped = [flip[x] for x in bit_string]

# 1

Write an expression which operates on `employees` and returns

```
['dopey', 'bashful', 'grumpy']
```

# 2

Write an expression which operates on `employees` and returns

```
y
```

employeeEmail['happy'][1][-1]

# 3

Write an expression which operates on `employeeEmail` and returns

```
"rump"
```

# 4

Write an expression which operates on `secret_word` and returns

```
'arian'
```

# 5

Write an expression which operates on `secret_word` and returns

```
[False, False, True, False, True, False, True, False, True, True, False]
```

# 6

`flipped` is defined above as

```
flipped = [flip[x] for x in bit_string]
```

The current value of `flipped` is

```
['1', '1', '0', '0', '0', '1']
```

Redefine `flip` so that the value of `flipped` becomes

```
[0, 0, 1, 1, 1, 0].
```


Part 5

In [14]:
import numpy as np
x = np.array([5,13,23,47,9])
y = np.ones((5,))
z = np.ones((5,2))

# a

Write out an expression which return the shape of `x`,

# b

Write out an expression which operates on and returns

```
array([10, 26, 46, 94, 18])
```

# c

Write out an expression that returns an array containing the elementwise sum of the elements in `x` and `y`.

# d

Consider:

In [ ]:
x + z

Explain why you get the result that you get for `x + z`. 

# e

Note the following:

In [31]:
x < 20

array([ True,  True, False, False,  True], dtype=bool)

The result above is called a **Boolean array** because it only contains instances of the
type `bool` (`True` and `False`). Such Boolean arrays can be used to index arrays (basically
if they are of the same length).  Using a Boolean array this way is called using a **Boolean mask**.

# e (ctd.)

Using a Boolean mask, write an expression that returns an array containing the members of `x` that
are less than `20`.

# f

Now consider

In [34]:
two_d_array = np.array([[1,2],[2,1],[5,5],[9,4]])
two_d_array

array([[1, 2],
       [2, 1],
       [5, 5],
       [9, 4]])

Write an expression that returns the second row of `two_d_array`.

Write an expression that returns `two_d_array` omitting the first row.

Write an expression that returns the following subarray of `two_d_array`.

```
array([[2, 1],
       [5, 5]])
```