## See Part Two (thisnotebook needs some editing)

In [34]:
# Hillshade index values [0,255]  1 byte
hillshade_9AM = data['feature_names'].index('Hillshade_9am')
hillshade_3PM = data['feature_names'].index('Hillshade_3pm')
col1 = data.data[:,hillshade_9AM]
col2 = data.data[:,hillshade_3PM]
col1.min(),col1.max(),col2.min(),col2.max()

(0.0, 254.0, 0.0, 254.0)

Example:  `data.data`  is a `numpy` array containing the attributes for the 581,012 samples.  


In [ ]:
print(type(data.data))
print(data.data.shape)

<class 'numpy.ndarray'>
(581012, 54)



To compute the Boolean array  that identifies the rows in which attribute 0 is greater than 3000 you do

In [ ]:
WW = data.data[:,0] > 3000
print(WW)
print(WW.shape, data.data.shape)

[False False False ... False False False]
(581012,) (581012, 54)


In [ ]:
WW.sum()

286266

Note the Boolean array has the same number of rows as the entire dataset.  To find the rows that satisfy this condition, you use this Boolean array as a 
**mask**. That is, you do:

In [ ]:
print(data.data[WW,:])
data.data[WW,:].shape

[[3008.   45.   14. ...    0.    0.    0.]
 [3073.  173.   12. ...    0.    0.    0.]
 [3067.  164.   11. ...    0.    0.    0.]
 ...
 [3125.  127.    5. ...    0.    0.    0.]
 [3126.  120.    4. ...    0.    0.    0.]
 [3124.  115.    5. ...    0.    0.    0.]]


(286266, 54)

Note the new array contains just the rows that satisfies condition `WW` , so it is smaller.

The covertypes (or dominant tree) for each forest plot are in `data.target`.  The `target` attribute is often the attribute used to store the classes in an `sklearn` clasification dataset. There are seven classes.

In [ ]:
print(data.target.shape)
print(set(data.target))

(581012,)
{1, 2, 3, 4, 5, 6, 7}


Place your answer to questions 1a and 1b in the next cell.

In [27]:
#The rows in the covertype dataset which have a value greater than 300 for attribute 1.
# The col indexed 1
data.data[:,1] 
# Boolean array for condition
B1 = data.data[:,1] > 300
# Question a. How many?
print(B1.sum())
# Question b. Which rows?
data.data[(data.data[:,1] > 300)]

102696


array([[2.686e+03, 3.540e+02, 1.200e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.699e+03, 3.470e+02, 3.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.570e+03, 3.460e+02, 2.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [2.619e+03, 3.360e+02, 1.300e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.630e+03, 3.170e+02, 1.200e+01, ..., 0.000e+00, 0.000e+00,
        0.000e+00],
       [2.633e+03, 3.090e+02, 9.000e+00, ..., 0.000e+00, 0.000e+00,
        0.000e+00]])

Place your answer to questions 2a and 2b in the next cell.

In [22]:
#The rows which have attribute 12 (Note: this is a qualitative soil attribute).
#B12 = data.data[:,12]  == True
B12 = data.data[:,12]  == 1
B12.sum()

253364

In [19]:
data.data[B12]

array([[2621.,  162.,   13., ...,    0.,    0.,    0.],
       [2664.,  112.,    5., ...,    0.,    0.,    0.],
       [2633.,   68.,    8., ...,    0.,    0.,    0.],
       ...,
       [2386.,  159.,   17., ...,    0.,    0.,    0.],
       [2384.,  170.,   15., ...,    0.,    0.,    0.],
       [2383.,  165.,   13., ...,    0.,    0.,    0.]])

In [11]:
set(data.data[:,12])

{0.0, 1.0}

In [12]:
True == 1

True

In [13]:
True == 1.0

True

In [14]:
isinstance(True, int)

True

In [15]:
True + 3

4

In [16]:
import math
math.sqrt(True)

1.0

Place your answer to questions 3a and 3b in the next cell.

In [23]:
# The entire covertypes dataset excluding rows which belong either to covertype 3 or covertype 5. 
# (Note: you will have to use two arrays data.data and data.target).
B3 = ~((data.target == 3)|(data.target == 5))
B3.sum()

535765

In [26]:
data.data[B3]

array([[2804.,  139.,    9., ...,    0.,    0.,    0.],
       [2785.,  155.,   18., ...,    0.,    0.,    0.],
       [2579.,  132.,    6., ...,    0.,    0.,    0.],
       ...,
       [2579.,   48.,   21., ...,    0.,    0.,    0.],
       [2571.,   55.,   21., ...,    0.,    0.,    0.],
       [2638.,  147.,   13., ...,    0.,    0.,    0.]])

In [10]:
set(data.target)

{1, 2, 3, 4, 5, 6, 7}

Place your answer to questions 4a and 4b in the next cell.

In [ ]:
# The rows which have attribute 12 but do not have either covertype 3 or covertype 5.

Place your answer to questions 5a and 5b in the next cell.

In [ ]:
# The rows which are not in covertype 3 or 5, 
# have a value greater than 300 for attribute 1, and have attribute 12.

### Part Two

Using pandas

In [1]:
from sklearn.datasets import fetch_covtype
import pandas as pd

# Fatch data.data as a pandas DataFrame
data = fetch_covtype(as_frame=True)
cover_df = data.data

In [158]:
print(data.DESCR)

.. _covtype_dataset:

Forest covertypes
-----------------

The samples in this dataset correspond to 30×30m patches of forest in the US,
collected for the task of predicting each patch's cover type,
i.e. the dominant species of tree.
There are seven covertypes, making this a multiclass classification problem.
Each sample has 54 features, described on the
`dataset's homepage <https://archive.ics.uci.edu/ml/datasets/Covertype>`__.
Some of the features are boolean indicators,
while others are discrete or continuous measurements.

**Data Set Characteristics:**

    =================   ============
    Classes                        7
    Samples total             581012
    Dimensionality                54
    Features                     int
    =================   ============

:func:`sklearn.datasets.fetch_covtype` will load the covertype dataset;
it returns a dictionary-like 'Bunch' object
with the feature matrix in the ``data`` member
and the target values in ``target``. If optional a

```
Attribute Information:

Given is the attribute name, attribute type, the measurement unit and a brief description. The forest cover type is the classification problem. The order of this listing corresponds to the order of numerals along the rows of the database.

Name / Data Type / Measurement / Description

Elevation / quantitative /meters / Elevation in meters
Aspect / quantitative / azimuth / Aspect in degrees azimuth
Slope / quantitative / degrees / Slope in degrees
Horizontal_Distance_To_Hydrology / quantitative / meters / Horz Dist to nearest surface water features
Vertical_Distance_To_Hydrology / quantitative / meters / Vert Dist to nearest surface water features
Horizontal_Distance_To_Roadways / quantitative / meters / Horz Dist to nearest roadway
Hillshade_9am / quantitative / 0 to 255 index / Hillshade index at 9am, summer solstice
Hillshade_Noon / quantitative / 0 to 255 index / Hillshade index at noon, summer soltice
Hillshade_3pm / quantitative / 0 to 255 index / Hillshade index at 3pm, summer solstice
Horizontal_Distance_To_Fire_Points / quantitative / meters / Horz Dist to nearest wildfire ignition points
Wilderness_Area (4 binary columns) / qualitative / 0 (absence) or 1 (presence) / Wilderness area designation
Soil_Type (40 binary columns) / qualitative / 0 (absence) or 1 (presence) / Soil Type designation
Cover_Type (7 types) / integer / 1 to 7 / Forest Cover Type designation
```

In [3]:
type(cover_df)

pandas.core.frame.DataFrame

In [4]:
type(data.target)

pandas.core.series.Series

In [5]:
cover_df

Elevation  Aspect  Slope  Horizontal_Distance_To_Hydrology  \
0          2596.0    51.0    3.0                             258.0   
1          2590.0    56.0    2.0                             212.0   
2          2804.0   139.0    9.0                             268.0   
3          2785.0   155.0   18.0                             242.0   
4          2595.0    45.0    2.0                             153.0   
...           ...     ...    ...                               ...   
581007     2396.0   153.0   20.0                              85.0   
581008     2391.0   152.0   19.0                              67.0   
581009     2386.0   159.0   17.0                              60.0   
581010     2384.0   170.0   15.0                              60.0   
581011     2383.0   165.0   13.0                              60.0   

        Vertical_Distance_To_Hydrology  Horizontal_Distance_To_Roadways  \
0                                  0.0                            510.0   
1                                 -6.0                            390.0   
2                                 65.0                           3180.0   
3                                118.0                           3090.0   
4                                 -1.0                            391.0   
...                                ...                              ...   
581007                            17.0                            108.0   
581008                            12.0                             95.0   
581009                             7.0                             90.0   
581010                             5.0                             90.0   
581011                             4.0                             67.0   

        Hillshade_9am  Hillshade_Noon  Hillshade_3pm  \
0               221.0           232.0          148.0   
1               220.0           235.0          151.0   
2               234.0           238.0          135.0   
3               238.0           238.0          122.0   
4               220.0           234.0          150.0   
...               ...             ...            ...   
581007          240.0           237.0          118.0   
581008          240.0           237.0          119.0   
581009          236.0           241.0          130.0   
581010          230.0           245.0          143.0   
581011          231.0           244.0          141.0   

        Horizontal_Distance_To_Fire_Points  ...  Soil_Type_30  Soil_Type_31  \
0                                   6279.0  ...           0.0           0.0   
1                                   6225.0  ...           0.0           0.0   
2                                   6121.0  ...           0.0           0.0   
3                                   6211.0  ...           0.0           0.0   
4                                   6172.0  ...           0.0           0.0   
...                                    ...  ...           ...           ...   
581007                               837.0  ...           0.0           0.0   
581008                               845.0  ...           0.0           0.0   
581009                               854.0  ...           0.0           0.0   
581010                               864.0  ...           0.0           0.0   
581011                               875.0  ...           0.0           0.0   

        Soil_Type_32  Soil_Type_33  Soil_Type_34  Soil_Type_35  Soil_Type_36  \
0                0.0           0.0           0.0           0.0           0.0   
1                0.0           0.0           0.0           0.0           0.0   
2                0.0           0.0           0.0           0.0           0.0   
3                0.0           0.0           0.0           0.0           0.0   
4                0.0           0.0           0.0           0.0           0.0   
...              ...           ...           ...           ...           ...   
581007           0.0           0.0           0.0           0.0           0.0   
5810

What is meant by saying we have 4 binary columns giving the wilderness area?

In [25]:
cover_df['Wilderness_Area_0']

0         1.0
1         1.0
2         1.0
3         1.0
4         1.0
         ... 
581007    0.0
581008    0.0
581009    0.0
581010    0.0
581011    0.0
Name: Wilderness_Area_0, Length: 581012, dtype: float64

`Wilderness_0` is a binary column containing only the values 0 and 1. 
Similarly for `Wilderness_1`,  `Wilderness_2`, and  `Wilderness_3`.

Do any rows belong to more than one wilderness type?  

In [13]:

Bwilderness10 = (cover_df['Wilderness_Area_0'] == 1.0) & (cover_df['Wilderness_Area_1'] == 1.0)
Bwilderness20 = (cover_df['Wilderness_Area_0'] == 1.0) & (cover_df['Wilderness_Area_2'] == 1.0)
Bwilderness30 = (cover_df['Wilderness_Area_0'] == 1.0) & (cover_df['Wilderness_Area_3'] == 1.0)
Bwilderness21 = (cover_df['Wilderness_Area_2'] == 1.0) & (cover_df['Wilderness_Area_1'] == 1.0)
Bwilderness31 = (cover_df['Wilderness_Area_3'] == 1.0) & (cover_df['Wilderness_Area_1'] == 1.0)
Bwilderness33 = (cover_df['Wilderness_Area_3'] == 1.0) & (cover_df['Wilderness_Area_2'] == 1.0)
Bwilderness10.any(),Bwilderness20.any(),Bwilderness30.any(),Bwilderness21.any(),\
     Bwilderness31.any(),Bwilderness33.any(),

(False, False, False, False, False, False)

No.

Let's collapse these four columns into one categorical column.  This will make it easier  to do grouping
defined by wilderness area.

`df.idxmax(axis=1)` returns a `Series` containing the column name of the column with the max value
for each row of `df` (it is the analog of `a.argmax(axis=1)` in `numpy`, which the returns 
a 1D array containing the index of the max value for each row in `a`).  We apply `.idxmax(axis=1)` to 
a `DataFrame` containing just the wilderness columns.

In [21]:
#df.idxmax(axis=1)
wa_col = cover_df.loc[:,'Wilderness_Area_0':'Wilderness_Area_3'].idxmax(axis=1)

In [15]:
wa_col

0         Wilderness_Area_0
1         Wilderness_Area_0
2         Wilderness_Area_0
3         Wilderness_Area_0
4         Wilderness_Area_0
                ...        
581007    Wilderness_Area_2
581008    Wilderness_Area_2
581009    Wilderness_Area_2
581010    Wilderness_Area_2
581011    Wilderness_Area_2
Length: 581012, dtype: object

Let's do a sanity check.  Did we lose any information?

First, get the value counts for our new column.

In [19]:
wa_col.value_counts()

Wilderness_Area_0    260796
Wilderness_Area_2    253364
Wilderness_Area_3     36968
Wilderness_Area_1     29884
dtype: int64

Now the value counts in `cover_df`, which is of course a little more awkward.  We need to sum 
each of the 4 columns.

In [18]:

col_counts = cover_df.loc[:,'Wilderness_Area_0':'Wilderness_Area_3'].sum()
## A series labeled by the col names
col_counts

Wilderness_Area_0    260796.0
Wilderness_Area_1     29884.0
Wilderness_Area_2    253364.0
Wilderness_Area_3     36968.0
dtype: float64

They look the same, but let's make it official
and do a programmatic check.  We sort the index of `wa_col.value_counts()` to line
up the two indices, and do `==`.

In [31]:
(wa_col.value_counts().sort_index() == col_counts)

Wilderness_Area_0    True
Wilderness_Area_1    True
Wilderness_Area_2    True
Wilderness_Area_3    True
dtype: bool

Ok.  So it's a valid conversion.  No information has been lost.  

Maybe it'll be useful for the problems below.  

### Exercises

Q1: What are the mean horizontal distances to hydrology for each cover type,
from highest to lowest?

Step One: Produce a `panda Series` whose index is the cover types and whose values
are the mean horizontal distance to hydrology. (Use groupby)

Step Two: Sort it from highest to lowest.

In [157]:
target_groups = data.data.groupby(data.target)
water_means = target_groups['Horizontal_Distance_To_Hydrology'].mean()
sorted_water = water_means.sort_values(ascending=False)
# A series indexed by cover type
sorted_water

Cover_Type
7    356.994686
2    279.916442
1    270.555245
5    212.354893
3    210.276473
6    159.853458
4    106.934838
Name: Horizontal_Distance_To_Hydrology, dtype: float64

Q2:  Which kind of wilderness area has the highest mean slope?

Produce a Series indexed by wilderness types. You can do this with
`groupby` but you need to either write a function that applies to `data.data` rows (actually
to row indices) and computes the wilderness type (see the groupby docs for using a function for grouping) or produce a sequence that assigns  the right wilderness type to each row.

In [1]:
# Idea:  take the sequence-that-assigns-wilderness-type route. Use wa_col (computed above).  
data.data.groupby(wa_col)['Slope'].mean()

NameError: name 'data' is not defined

Solution two:

Use a function on rows with groupby to find the same grouping.

Note that the grouping operation with a function is significantly slower
than it is using a pre-computed column

In [190]:
def get_wild_type(row):
    # return the index of the selected column that has a 1 in it
    # row[col_i:col_j].argmax() -> the index 0-(n-1) of the n selected cols that has a 1 in it.
    # assuming row[col_i:col_j] is a sequence of binary cols with a unique 1 in each row.
    return data.data.loc[:,'Wilderness_Area_0':'Wilderness_Area_3'].iloc[row].argmax()

gg = data.data.groupby(get_wild_type)
gg['Slope'].mean()

0    12.157292
1    12.937893
2    15.173786
3    21.443438
Name: Slope, dtype: float64

Q3:  What are the mean elevations for each wilderness area type?

Produce a Series indexed by wilderness area types. You can do this with
`groupby` but you need to either write a function that applies to rows
and computes the wilderness type (see the groupby docs for using a function for grouping)
or produce a sequence that assigns  the right wilderness type to each row.

In [129]:

elevation_means = data.data.groupby(wa_col)['Elevation'].mean()
elevation_means

Wilderness_Area_0    3000.267286
Wilderness_Area_1    3245.727814
Wilderness_Area_2    2980.554471
Wilderness_Area_3    2294.106038
Name: Elevation, dtype: float64

Solution two:

Use a function on rows to find the same grouping.

In [155]:
# Commented out because it's a costly computation
# and it's the same gg we computed for the last problem
# gg = data.data.groupby(get_wild_type)
gg['Elevation'].mean()

0    3000.267286
1    3245.727814
2    2980.554471
3    2294.106038
Name: Elevation, dtype: float64

Note we can also produce a `DataFrame` for the
combined results from last two 
problems by just doing:

In [156]:
gg[['Slope','Elevation']].mean()

Slope    Elevation
0  12.157292  3000.267286
1  12.937893  3245.727814
2  15.173786  2980.554471
3  21.443438  2294.106038

### Q4

a.  Construct a DataFrame `cts` which for each cover type  c and each soil type s gives the percentage
of plots of type c with soil of type s. Hint One: Start by constructing a `Series` that gives the soil type 
of each row of `data.data`. Hint Two: Read the docs for `pd.crosstab()`.

b. Use `cts` to find the dominant soil type for each cover type. (Hint: Use `.idxmax()`)

c. Write an expression that selects the cover types that have one soil type in over 50% of the sampled plots.

d.  Construct a DataFrame `cts_r` which for each cover type  c and each soil type s gives the percentage
of plots with soil type s that are of cover type c.

e. Use `cts_r` to find the dominant cover type for each soil type.

f. Write an expression that selects the soil types that can only be found with a single cover type.

### Solutions (Q4 a. - f.)

Q4a.  Construct a DataFrame `cts` which for each cover type  c and each soil type s gives the percentage
of plots of type c with soil of type s.

In [308]:


# a.

from IPython.core.display import display, HTML

# Making the categorical column
st_col = data.data.loc[:,'Soil_Type_0':'Soil_Type_39'].idxmax(axis=1)
st_col.name = "Soil"
cts0 = pd.crosstab(st_col, data.target,normalize='columns')
#  Sort undex for aesthetics
cts = cts0.sort_index(key=lambda idx: pd.Index(int(x[10:]) for x in idx))
#  Suppress some decimal places in printout
with pd.option_context('display.float_format', lambda x: f"{x:.3f}"): 
    # To get standard HTML rendering of DF + display context
    display(HTML(cts.to_html()))
    # This works but omits HTML rendering (e.g. no boldface)
    # print(cts)

Checking the percentages are columnwise:

In [255]:
cts.sum(axis=0)

Cover_Type
1    1.0
2    1.0
3    1.0
4    1.0
5    1.0
6    1.0
7    1.0
dtype: float64

Q4b. What is the dominant soil type for each cover type?

In [276]:
dominant_soil_types = pd.DataFrame({"type":cts.idxmax(),"pct":cts.max()})
dominant_soil_types

type       pct
Cover_Type                        
1           Soil_Type_28  0.197843
2           Soil_Type_28  0.252025
3            Soil_Type_9  0.322537
4            Soil_Type_2  0.370586
5           Soil_Type_29  0.222374
6            Soil_Type_9  0.510105
7           Soil_Type_37  0.297611

Q4c. What cover types have one soil type in over 50% of the sampled plots?

In [277]:
dominant_soil_types[dominant_soil_types['pct']>.5]

type       pct
Cover_Type                       
6           Soil_Type_9  0.510105

Q4d.  Construct a DataFrame `cts_r` which for each cover type  c and each soil type s gives the percentage
of plots with soil type s that are of cover type c.

In [310]:
# d. Now need to normalize the ROWS. The next line is the essential soln.  The rest is about display.
cts1 = pd.crosstab(st_col, data.target, normalize='index')
cts_r = cts1.sort_index(key=lambda idx: pd.Index(int(x[10:]) for x in idx))
with pd.option_context('display.float_format', lambda x: f"{x:.3f}"): 
    display(HTML(cts_r.to_html()))

In [289]:
cts_r.sum(axis=1)

Soil
Soil_Type_0     1.0
Soil_Type_1     1.0
Soil_Type_2     1.0
Soil_Type_3     1.0
Soil_Type_4     1.0
Soil_Type_5     1.0
Soil_Type_6     1.0
Soil_Type_7     1.0
Soil_Type_8     1.0
Soil_Type_9     1.0
Soil_Type_10    1.0
Soil_Type_11    1.0
Soil_Type_12    1.0
Soil_Type_13    1.0
Soil_Type_14    1.0
Soil_Type_15    1.0
Soil_Type_16    1.0
Soil_Type_17    1.0
Soil_Type_18    1.0
Soil_Type_19    1.0
Soil_Type_20    1.0
Soil_Type_21    1.0
Soil_Type_22    1.0
Soil_Type_23    1.0
Soil_Type_24    1.0
Soil_Type_25    1.0
Soil_Type_26    1.0
Soil_Type_27    1.0
Soil_Type_28    1.0
Soil_Type_29    1.0
Soil_Type_30    1.0
Soil_Type_31    1.0
Soil_Type_32    1.0
Soil_Type_33    1.0
Soil_Type_34    1.0
Soil_Type_35    1.0
Soil_Type_36    1.0
Soil_Type_37    1.0
Soil_Type_38    1.0
Soil_Type_39    1.0
dtype: float64

Q4e. What is the dominant cover type for each soil type?

In [282]:
dominant_covers = pd.DataFrame({"type":cts_r.idxmax(axis=1),
                                "pct": cts_r.max(axis=1)})
dominant_covers.sort_values("pct",ascending=False)

type       pct
Soil                        
Soil_Type_36     7  1.000000
Soil_Type_6      2  1.000000
Soil_Type_14     6  1.000000
Soil_Type_20     1  0.959427
Soil_Type_27     2  0.941860
Soil_Type_11     2  0.910146
Soil_Type_33     2  0.888268
Soil_Type_17     2  0.873618
Soil_Type_8      2  0.859634
Soil_Type_25     2  0.839706
Soil_Type_21     1  0.772571
Soil_Type_12     2  0.760599
Soil_Type_7      2  0.759777
Soil_Type_24     2  0.736287
Soil_Type_10     2  0.731426
Soil_Type_0      3  0.693171
Soil_Type_29     2  0.670136
Soil_Type_1      3  0.663256
Soil_Type_28     2  0.619530
Soil_Type_22     1  0.615684
Soil_Type_15     2  0.612654
Soil_Type_18     1  0.612037
Soil_Type_5      3  0.607300
Soil_Type_4      3  0.605510
Soil_Type_3      3  0.605115
Soil_Type_38     1  0.570911
Soil_Type_31     2  0.562768
Soil_Type_19     2  0.562372
Soil_Type_37     1  0.560521
Soil_Type_32     2  0.560482
Soil_Type_26     1  0.556169
Soil_Type_39     1  0.551543
Soil_Type_13     6  0.547579
Soil_Type_35     7  0.529412
Soil_Type_23     1  0.524673
Soil_Type_30     2  0.514650
Soil_Type_34     7  0.501322
Soil_Type_2      3  0.499896
Soil_Type_9      3  0.353374
Soil_Type_16     2  0.279661

Q4f. What soil types can only be found with a single cover type?

In [275]:
dominant_covers[dominant_covers['pct'] == 1.0]

type  pct
Soil                   
Soil_Type_6      2  1.0
Soil_Type_14     6  1.0
Soil_Type_36     7  1.0