Name:

Red ID:

## Numpy Quiz 2017

Use the values defined in the code below for the next few problems.

In [2]:
import numpy as np
x = np.array([2,3,1,0])
y =np.arange(8)
z = 5 + x

What is the value of `y`?

In [3]:
y

array([0, 1, 2, 3, 4, 5, 6, 7])

What is the value of `z`?

In [5]:
z

array([7, 8, 6, 5])

Write an expression on the next line to retrieve 3 from `x`.

In [6]:
x[1]

3

Write an expression on the next line to retrieve 7 from `y`.

In [7]:
print y[-1]
print y[7]


7
7


In [ ]:
Write an expression on the next line to retrieve 5 from `z`.

In [8]:
print z[-1]
print z[3]

5
5


On the next line, write an expression that generates a 3 by 4 array filled with zeros.

In [9]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

<style>
    @font-face {
        font-family: "Computer Modern";
        src: url('http://mirrors.ctan.org/fonts/cm-unicode/fonts/otf/cmunss.otf');
    }
    div.cell{
        width:800px;
        margin-left:16% !important;
        margin-right:auto;
    }
    h1 {
        font-family: Helvetica, serif;
    }
    h4{
        margin-top:12px;
        margin-bottom: 3px;
       }
    div.text_cell_render{
        font-family: Computer Modern, "Helvetica Neue", Arial, Helvetica, Geneva, sans-serif;
        line-height: 145%;
        font-size: 130%;
        width:800px;
        margin-left:auto;
        margin-right:auto;
    }
    .CodeMirror{
            font-family: "Source Code Pro", source-code-pro,Consolas, monospace;
    }
    .text_cell_render h5 {
        font-weight: 300;
        font-size: 22pt;
        color: #4057A1;
        font-style: italic;
        margin-bottom: .5em;
        margin-top: 0.5em;
        display: block;
    }
    
    .warning{
        color: rgb( 240, 20, 20 )
        }  

In the next cell write an expression that produces an array containing result of multiplying 7 by each of the first 12 integers (1 - 12). There’s a hard way to do this and an easy way. The easy way uses elementwise operations.

In [10]:
#Hard way
print np.array([7*x for x in np.arange(1,13)])
# Easy way
print 7 * np.arange(1,13)

[ 7 14 21 28 35 42 49 56 63 70 77 84]
[ 7 14 21 28 35 42 49 56 63 70 77 84]


In [1]:
import numpy as np
room_matrix = \
np.array(
[[2,  3, 3, 1],
[5,  3, 3, 2],
[8,  3, 6, 2],
[5,  1, 3, 1],
[10, 4, 7, 2]])


In the line below, write an expression that retrieves the last row of `room_matrix`.  Also write down the value returned by that expression.

In [14]:
print room_matrix[-1]
print room_matrix[4]

[10  4  7  2]
[10  4  7  2]


In the next cell, write an expression that retrieves the third columns of `room_matrix`.

In [15]:
print room_matrix[:,2]
print room_matrix[:,-2]

[3 3 6 3 7]
[3 3 6 3 7]


In the next cell write an expression that retrieves the first two elements of the second column of `room_matrix`.

In [16]:
print room_matrix[0:2,1]
print room_matrix[:2,1]

[3 3]
[3 3]


In the next cell write an expression that retrieves the following submatrix from `room_matrix`:

```
array([[3,3],
       [3,3]])
```

In [20]:
print room_matrix[0:2,1:3]
print room_matrix[0:2,1:-1]
print room_matrix[0:-3,1:3]

[[3 3]
 [3 3]]
[[3 3]
 [3 3]]
[[3 3]
 [3 3]]


In the next cell, write an expression that returns a Boolean array that identifies the members of room_matrix which are equal to 2. Hint: Call the correct answer to this question ans. ans will return an array with shape 5x4. ans[i,j] == True if and only if room_matrix[i,j] == 2.

In [2]:
print room_matrix
room_matrix == 2

[[ 2  3  3  1]
 [ 5  3  3  2]
 [ 8  3  6  2]
 [ 5  1  3  1]
 [10  4  7  2]]


array([[ True, False, False, False],
       [False, False, False,  True],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False, False,  True]], dtype=bool)

In the next cell, write an expression that uses ans, the Boolean array you created in the last problem, to return the members of room_matrix that are equal to 2. Hint: There are four members of room_matrix that are equal to 2. The correct answer to this question returns a 1D array of length 4.

In [3]:
room_matrix[room_matrix == 2]

array([2, 2, 2, 2])