### Matrix Multiplication

In [1]:
import numpy as np

M = np.array([[3,0],[0,-5]])

v = np.array([1,2])
M@v


array([  3, -10])

Not to be confused with multiplication, which always does scalar multiplication, sometimes with
the help of broadcasting.  In
the case of `M` and `v`, the scalars in `v` will muliply the corresponding columns in `M`.

In [23]:
M*v

array([[  3,   0],
       [  0, -10]])

## Eigenvectors and eigenvalues

In [3]:
evals, evecs = np.linalg.eig(M)
evals, evecs

(array([ 3., -5.]),
 array([[1., 0.],
        [0., 1.]]))

In [4]:
def check_evals_evecs (evals,evecs):
    for idx in range(len(evals)):
        display(M@evecs[:,idx])
        display(evals[idx]*evecs[idx])
        print()


check_evals_evecs (evals,evecs)

array([3., 0.])

array([3., 0.])

array([ 0., -5.])

array([-0., -5.])

### Checking without a loop

Matrix multiplication will apply `M` successively to each column of `evecs` without a loop.

In [12]:
M@evecs

array([[ 3.,  0.],
       [ 0., -5.]])

The rules of broadcasting will ensure that the scalars in `evals` will get multipleid by the corresponding
columns

In [13]:
evals*evecs

array([[ 3., -0.],
       [ 0., -5.]])

In [16]:
def check_evals_evecs (evals,evecs):
    display(M@evecs)
    display(evals*evecs)

check_evals_evecs (evals,evecs)

array([[ 3.,  0.],
       [ 0., -5.]])

array([[ 3., -0.],
       [ 0., -5.]])