# Part 1 Containers   28 POINTS

You must execute the next cell, which we will refer to as the **data cell**, to do the problems in this section.

In [1]:
# Data cell

epsilon_left = 'abcde'
epsilon_right = 'zyxwv'
epsilon = list(zip(epsilon_right,epsilon_left))
fruit = ['tomato','cabbage','rambutan','persimmon','mangosteen']
frittata = {'alpha': epsilon_right + epsilon_left,
            'beta': epsilon_left + epsilon_right,
            'delta': fruit,
            'gamma': dict(epsilon)}

Using the containers in the data cell, write a single Python expression (so, **not** a for-loop) which returns the given values.  Sometimes there are actually many possible answers.  Try for the simplest.

### 1.1  4 POINTS

Return '`de`'

In [9]:
epsilon_left[-2:]

'de'

### 1.2   4 POINTS

Return '`wvab`'

In [2]:
frittata['alpha'][3:7]

'wvab'

In [3]:
epsilon_right[-2:] + epsilon_left[:2]

'wvab'

### 1.3   4 POINTS

Return `'rambutan'`.

In [13]:
fruit[2]

'rambutan'

### 1.4    4 POINTS

Return '`sim`'

In [12]:
frittata['delta'][3][3:6]

'sim'

In [4]:
fruit[3][3:6]

'sim'

### 1.5  4 POINTS

Return {'z': 'a', 'y': 'b', 'x': 'c', 'w': 'd', 'v': 'e'}

In [15]:
frittata['gamma']

{'z': 'a', 'y': 'b', 'x': 'c', 'w': 'd', 'v': 'e'}

### 1.6   4 POINTS

Return 

`[('x', 'c'), ('w', 'd')]`

In [16]:
epsilon[2:4]

[('x', 'c'), ('w', 'd')]

### 1.7   4 POINTS

Compare the results in the next two cells.

Explain why one expression raises an `Exception` and the other does not, even
though both involve accessing data defined in `epsilon`.

In [20]:
epsilon['x']

TypeError: list indices must be integers or slices, not str

In [19]:
frittata['gamma']['x']

'c'

# Part 2 Functions, Loops  24 POINTS

You must execute the data cell to do the problems in this section.

In [6]:
# Data cell

import numpy as np

xx = np.arange(0,26,4)

sad_story = """Billy the Kid lived in the Wild West long ago .
He was an outlaw .
He was friends with Pat Garrett who was a lawman .
One day Pat Garrett had to bring Billy the Kid in .
Billy would not come .
They had a gunfight and Pat shot his friend Billy .
"""

###  2.1   4 POINTS

Write a loop (it can be a list comprehension) that computes a list of the numbers in `xx` that arew divisible by 3.

Do not import any python packages to help (that would suggest that you have
not been doing the material in the first part of the class and have done a google search to solve this problem).

You may find it useful to be reminded of the `%`-operator:

x%y

returns the remainder when x is divided by y.  So, for example,

```
>>> 17%5
2
```

Note: although `xx` is a numpy array, for the purposes of this section you
may treat it as if it were a list.

In [26]:
[x for x in xx if x%3 ==0]

[0, 12, 24]

###  2.2    4 POINTS

Write a for-loop (it may be a list comprehension) that builds a list containing all instances of the letter  `t` in `sad_story`

In [28]:
[l for l in sad_story if l == 't']

['t',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't',
 't']

### 2.3   4 POINTS

Write a for-loop (it may be a list comprehension) that builds a list containing all instances of the word  `the` in `sad_story`.

In [29]:
[w for w in sad_story.split() if w == 'the']

['the', 'the', 'the']

### 2.4    4 POINTS

Write a for loop that creates a dictionary containing the counts of all the words
in `sad_story`.  Do not import any Python modules. 

Call your dictonary `wd_cts`.  If your program is correct `wd_cts`
should contain the following count:

```
>>> wd_counts['in']
2
```

In [7]:
wd_cts = dict()
for wd in sad_story.split():
    if wd in wd_cts:
        wd_cts[wd] += 1
    else:
        wd_cts[wd] = 1

wd_cts['in']

2

In [8]:
wd_cts

{'Billy': 4,
 'the': 3,
 'Kid': 2,
 'lived': 1,
 'in': 2,
 'Wild': 1,
 'West': 1,
 'long': 1,
 'ago': 1,
 '.': 6,
 'He': 2,
 'was': 3,
 'an': 1,
 'outlaw': 1,
 'friends': 1,
 'with': 1,
 'Pat': 3,
 'Garrett': 2,
 'who': 1,
 'a': 2,
 'lawman': 1,
 'One': 1,
 'day': 1,
 'had': 2,
 'to': 1,
 'bring': 1,
 'would': 1,
 'not': 1,
 'come': 1,
 'They': 1,
 'gunfight': 1,
 'and': 1,
 'shot': 1,
 'his': 1,
 'friend': 1}

###  2.5   4 POINTS

Write a **function** `find_word_forms` that takes a string `text_str` and a word `form` as its **two** arguments and returns all **words** in `text_str` that end with `form`.
Write this without importing any Python modules.

Here are some tests that your function should pass:

```
>>> find_word_forms(sad_story, 'ing')
['bring']
>>> find_word_forms(sad_story, 'ed')
['lived']
>>> find_word_forms("He 's sending birds on the wing .", 'ing')
['sending', 'wing']
>>> find_word_forms(sad_story, 'g')
['long', 'bring']
```

Hint:  You may find it helpful to remember the
string method `endswith`.

In [33]:
def find_word_forms (text_str, form):
    return [wd for wd in text_str.split() if wd.endswith(form)]

### 2.6   4 POINTS

Write a function that converts degrees to radians. You are allowed
to use the following import statement:

```
from numpy import pi
```

The formula is

```
Radians = (Degrees/360) * 2 * pi
```

Here are some tests

```
>>> deg2rad(360)
6.283185307179586
>>> deg2rad(90)
1.5707963267948966
>>> deg2rad(72)
1.2566370614359172
```

In [109]:
from numpy import pi

def deg2rad (deg):
    return (deg/360) * 2 * pi

# Part 3 Numpy arrays    24 POINTS

You must execute the next cell to do the problems in this section.

In [56]:
# Data cell

import numpy as np

xx = np.arange(4,61,4)

yy = xx.reshape((3,5))

### 3.1    4 POINTS

Write a single Python expression that returns 12 from `xx`

In [58]:
xx[2]

12

### 3.2    4 POINTS

Write a single Python expression  that returns all members of `xx` divisible by 8.
Hint: Use a splice.

In [60]:
xx[1::2]

array([ 8, 16, 24, 32, 40, 48, 56])

###  3.3 4 POINTS

Write a single Python expression  that returns all members of `xx` 
greater than 16.  You may use a splice if you wish.

In [68]:
xx[4:]

array([20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

### 3.4   4 POINTS

Write a single Python expression  that returns the following
1D array from `yy`.

```
array([24, 28, 32, 36, 40])
```

In [67]:
yy[1]

array([24, 28, 32, 36, 40])

### 3.5 4 POINTS

Write a single Python expression  that returns the following
2D array from `yy`.

```
array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40]])
```

In [66]:
yy[:2]

array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40]])

### 3.6    4 POINTS

Write a single Python expression  that returns the following
2D array from `yy`.

```
array([[32, 36],
       [52, 56]])
```

In [65]:
yy[1:3, 2:4]

array([[32, 36],
       [52, 56]])

# Part 4  Wine Data  24 POINTS



In this exercise set, we load wine data. This is a multi class dataset that has data for three different wine types  (stored in `target` below) corresponding to three
different cultivators in a particular region of Italy.  These will just
be referred to as class_1 calss_2 and class_3 in the description below
and in the questions.
The chemical properties of the wine stored in the 2D numpy array `data` below are sufficient to identity the cultivator, but it's a challenging classification problem.

Wine recognition dataset
-----------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
     
    The wine atributes listed in their column order.
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Magnesium:                    70.0 162.0    99.7  14.3
    Total Phenols:                0.98  3.88    2.29  0.63
    Flavanoids:                   0.34  5.08    2.03  1.00
    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
    Proanthocyanins:              0.41  3.58    1.59  0.57
    Colour Intensity:              1.3  13.0     5.1   2.3
    Hue:                          0.48  1.71    0.96  0.23
    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
    Proline:                       278  1680     746   315
    ============================= ==== ===== ======= =====

    :Missing Attribute Values: None
    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners: 

Forina, M. et al, PARVUS - 
An Extendible Package for Data Exploration, Classification and Correlation. 
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science. 

You must evaluate the next cell to do the problems in this section.

In [84]:
# Data cell

from sklearn.datasets import load_wine
wdata = load_wine()
data = wdata.data
target = wdata.target

### 4.0   4 POINTS

Write a Python expression that returns s Boolean array defining
the set of rows of the `data` array with magnesium level greater than 99.7  and 
Proanthocyanins level less than 1.59.

In [78]:
B4_1 = (data[:,4] > 99.7) & (data[:,8] < 1.59)

### 4.1 5 POINTS

Write a Python expression that returns the rows of the `data` array 
representing  wine samples with  magnesium level greater than 99.7  and 
Proanthocyanins level less than 1.59.

In [81]:
data[B4_1]

### 4.2  5 POINTS

How many such rows are there?

In [80]:
B4_1.sum()

35

### 4.3 5 POINTS

Write a Python expression that returns the rows of the `data` array 
representing wine samples such that they are not of class_1 and they
have magnesium level greater than 99.7  and 
Proanthocyanins level less than 1.59.

In [82]:
B4_3 = ~(target == 1) & B4_1
data[B4_3]

array([[1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.406e+01, 2.150e+00, 2.610e+00, 1.760e+01, 1.210e+02, 2.600e+00,
        2.510e+00, 3.100e-01, 1.250e+00, 5.050e+00, 1.060e+00, 3.580e+00,
        1.295e+03],
       [1.363e+01, 1.810e+00, 2.700e+00, 1.720e+01, 1.120e+02, 2.850e+00,
        2.910e+00, 3.000e-01, 1.460e+00, 7.300e+00, 1.280e+00, 2.880e+00,
        1.310e+03],
       [1.376e+01, 1.530e+00, 2.700e+00, 1.950e+01, 1.320e+02, 2.950e+00,
        2.740e+00, 5.000e-01, 1.350e+00, 5.400e+00, 1.250e+00, 3.000e+00,
        1.235e+03],
       [1.351e+01, 1.800e+00, 2.650e+00, 1.900e+01, 1.100e+02, 2.350e+00,
        2.530e+00, 2.900e-01, 1.540e+00, 4.200e+00, 1.100e+00, 2.870e+00,
        1.095e+03],
       [1.328e+01, 1.640e+00, 2.840e+00, 1.550e+01, 1.100e+02, 2.600e+00,
        2.680e+00, 3.400e-01, 1.360e+00, 4.600e+00, 1.090e+00, 2.780e+00,
        8.80

### 4.4 5 POINTS

How many such rows are there?

In [83]:
B4_3.sum()

27