# Part 1 Containers  28 points

You must execute the next cell, which we will refer to as the **data cell**, to do the problems in this section.

In [43]:
# Data cell

epsilon_left = 'abcde'
epsilon_right = 'zyxwv'
epsilon = list(zip(epsilon_left,epsilon_right))
fruit = ['tomato','cabbage','persimmon','rambutan','mangosteen']
frittata = {'alpha': epsilon_left + epsilon_right,
            'beta': epsilon_right + epsilon_left,
            'delta': fruit,
            'gamma': dict(epsilon)}

Using the containers in the data cell, write a single Python expression (so, **not** a for-loop) which returns the given values.  Sometimes there are actually many possible answers.  Try for the simplest.

# 1.1  4 points

Return '`bc`'

In [37]:
epsilon_left[1:3]

'bc'

# 1.2  4 points

Return '`dezy`'

In [44]:
frittata['alpha'][3:7]

'dezy'

#### Wrong answers

In [66]:
epsilon_left[-2:] + epsilon_right[:2]

'dezy'

Too complicated.  Inspect your containers and learn about
the structure that has already been built for you.

The idea is that you are not just passive recipients of
the data in the data cell above.  You **inspect** your data,
by evaluating cells like the following.

In [63]:
frittata

{'alpha': 'abcdezyxwv',
 'beta': 'zyxwvabcde',
 'delta': ['tomato', 'cabbage', 'persimmon', 'rambutan', 'mangosteen'],
 'gamma': {'a': 'z', 'b': 'y', 'c': 'x', 'd': 'w', 'e': 'v'}}

In [62]:
frittata['alpha']

'abcdezyxwv'

# 1.3  4 points

Return `'persimmon'`.

In [49]:
fruit[2]

'persimmon'

# 1.4  4 points

Return '`but`'

In [46]:
frittata['delta'][3][3:6]

'but'

# 1.5  4 points

Return '`{'a': 'z', 'b': 'y', 'c': 'x', 'd': 'w', 'e': 'v'}`'

In [38]:
frittata['gamma']

{'a': 'z', 'b': 'y', 'c': 'x', 'd': 'w', 'e': 'v'}

People tried all kinds of things (sometimes unsuccessfully) to get their dictionaries to print out in the order given above. 
When this got overly complicated or incorrect, it was a deduction.

But a dictionary is a **set** of key-value pairs so `frittata['gamma']` is always == to a dictionary with the same key value pairs, no matter what order the key-value pairs were added to the dictionary in.  

In [54]:
import random
 
# Make a list of the key value pairs from frittata['gamma']
L = list(frittata['gamma'].items())
print(L)
# Use this great shuffle function from the random module
random.shuffle(L)
print(L)
new_dict = dict(L)
print(frittata['gamma'])
print(new_dict)
frittata['gamma'] == new_dict

[('a', 'z'), ('b', 'y'), ('c', 'x'), ('d', 'w'), ('e', 'v')]
[('a', 'z'), ('c', 'x'), ('e', 'v'), ('d', 'w'), ('b', 'y')]
{'a': 'z', 'b': 'y', 'c': 'x', 'd': 'w', 'e': 'v'}
{'a': 'z', 'c': 'x', 'e': 'v', 'd': 'w', 'b': 'y'}


True

# 1.6  4 points

Return 

`[('c', 'x'), ('d', 'w')]`

In [51]:
epsilon[2:4]

[('c', 'x'), ('d', 'w')]

# 1.7  4 points

Compare the results in the next two cells.

Explain why one expression raises an `Exception` and the other does not, even
though both involve accessing data defined in `epsilon`.

In [52]:
epsilon['c']

TypeError: list indices must be integers or slices, not str

In [53]:
frittata['gamma']['c']

'x'

The container `epsilon` is a list of pairs; the container `frittata['gamma']` is a dictionary.  A list is a sequence and must be indexed by  an integer indicating position in the sequence.  A dictionary is a set of key-value pairs and must be indexed by keys.
Hence, `epsilon['c']` is an error, and `frittata['gamma']['c']` is not. In particular `'c'` is one of the keys for the dictionary 
`frittata['gamma']`:

In [55]:
frittata['gamma']

{'a': 'z', 'b': 'y', 'c': 'x', 'd': 'w', 'e': 'v'}

# Part 2 Functions, Loops  24 points

You must execute the data cell to do the problems in this section.

In [5]:
# Data cell

import numpy as np

xx = np.arange(0,22,3)

sad_story = """Billy the Kid lived in the Wild West long ago .
He was an outlaw .
He was friends with Pat Garrett who was a lawman .
One day Pat Garrett had to bring Billy the Kid in .
Billy would not come .
They had a gunfight and Pat shot his friend Billy .
"""

### 2.1  4 points

Write a loop (it can be a list comprehension) that computes a list of the odd numbers in `xx`.

Do not import any python packages to help (that would suggest that you have
not been doing the material in the first part of the class and have done a google search to solve this problem).

You may find it useful to be reminded of the `%`-operator:

x%y

returns the remainder when x is divided by y.  So, for example,

```
>>> 17%3
2
```

Note: although `xx` is a numpy array, for the purposes of this section you
may treat it as if it were a list.

In [59]:
[x for x in xx if x%2 ==1]

[3, 9, 15, 21]

In [5]:
result = []

for n in xx:
    if n%2 == 1:
        result.append(n)
        
result

[3, 9, 15, 21]

### 2.2  4 points

Write a for-loop (it may be a list comprehension) that builds a list containing all instances of the letter  `f` in `sad_story`

In [62]:
[l for l in sad_story if l == 'f']

['f', 'f', 'f']

Alternatively:

In [4]:
result = []

for char in sad_story:
    if char == 'f':
        result.append(char)
        
result

['f', 'f', 'f']

####  wrong answer

JMG -2  What was requested was a list of letter instances not word instances.  No `.split()` needed.

The idea here is to test your flexibility.  You are able to modify your code to fit the exact specs written, rather than modifying the specs to fit what you know how to write.

In [68]:
wrong_result = []

for wd in sad_story.split():
    if 'f' in wd:
        wrong_result.append(wd)
        
wrong_result

['friends', 'gunfight', 'friend']

### 2.3  4 points

Write a for-loop (it may be a list comprehension) that builds a list containing all instances of the word  `Kid` in `sad_story`.

In [66]:
[w for w in sad_story.split() if w == 'Kid']

['Kid', 'Kid']

In [3]:
result = []

for w in sad_story.split():
    if w == 'Kid':
        result.append(w)
        
result

['Kid', 'Kid']

###  2.4  4 points

Write a for loop that creates a dictionary containing the counts of all the words
in `sad_story`.  Do not import any Python modules. 

Call your dictonary `wd_cts`.  If your program is correct `wd_cts`
should contain the following count:

```
>>> wd_counts['in']
2
```

In [19]:
wd_cts = dict()
for wd in sad_story.split():
    if wd in wd_cts:
        wd_cts[wd] += 1
    else:
        wd_cts[wd] = 1

wd_cts['in']

2

In [24]:
wd_cts['Billy']

4

#### 2.4 Some bad solutions

#### Using .count

We're going to  look at a bad solution that many of you found,
using the `count` method for sequences.  Here is an example.

In [25]:
ct_dict = dict()

word_list = sad_story.split()

for word in word_list:
    ct_dict[word] = word_list.count(word)
    
ct_dict['Billy']

4

In [26]:
ct_dict = dict()

word_list = sad_story.split()

print("story length", len(word_list))
print()
for word in word_list:
    if word == 'Billy':
        print(word, word_list.count(word))
    ct_dict[word] = word_list.count(word)

story length 55

Billy 4
Billy 4
Billy 4
Billy 4


The loop was wasteful.  The method ".count" loops through `word_list` each time it is called, 
so you are looping through `word_list` 55 times,
because you call count 55 times, once for each of the 55 words in `word_list`.  The recommended solution above loops through `word_list` once, computing the counts correctly.

#### Computing the same thing many times

One of the reasons you store the result of a computation in a variable is so that you wont have to that computation twice.

Consider this "dictionary comprehension" version of the 
.count solution, which illustrates a kind of Pythonic style
sometimes called "Always do it all in one line," because
it used to be considered a very cool feature of Python that so many
complicated thiongs could be done in one line.

In [11]:
# dictonary comprehension
wd_cts2 = {key: sad_story.replace(".", "").split().count(key) 
             for key in set(sad_story.replace(".", "").split())}


This code would both be more readable and more efficient
if we abandoned the 
"do it all in one line" philosophy.  Suppose we did 
the following at the beginning of our code.

In [9]:
word_list = sad_story.replace(".", "").split()

Then our dictionary comprehension would read

In [27]:
wd_cts3 = {key: word_list.count(key) for key in set(word_list)}

We have improved our code.  Why?

**Readability**:  It's now clear what we're doing because
we separate out the splitting into a list from the
counting.

**Efficiency**:  Moreover by
placing the expression defining `word_list` after `key:` in our original dictionary comprehension 
we were splitting and editing that same string once each time
through the loop, that is, 35 times --- each time
computing the same word_list --- so the "do it all
in one line" philosophy led  to a considerable
loss in efficiency. 

In this  revised version,
the string is split and edited only once,
gaining efficiency along with readability.


Note:  The dictionary comprehension using `.count`
is more efficient than the for-loop version because it 
loops through the set of words in `sad_story` instead of
the list.

In [12]:
len(set(word_list))

35

This is better because you  aren't computing the
the count of `Billy` 4 times, but tt's still a version
of the .count solution. It still loops through
all of word list for each word in the vocabulary (35 times),
so it's still wasteful.  Because the counting can be done
in one pass.

In [ ]:
wd_cts3 = {key: word_list.count(key) for key in set(word_list)}

#### .split vs .split(' ')

Let's return to the "right " solution but with one variant,
using `.split(' ')` instead of `.split()`.

In [20]:
word_list2 = sad_story.split(' ')
wd_cts4 = dict()
for wd in word_list2:
    if wd in wd_cts4:
        wd_cts4[wd] += 1
    else:
        wd_cts4[wd] = 1

wd_cts4['in']

2

Something went wrong.

In [23]:
wd_cts4['Billy']

3

In [21]:
wd_cts4

{'Billy': 3,
 'the': 3,
 'Kid': 2,
 'lived': 1,
 'in': 2,
 'Wild': 1,
 'West': 1,
 'long': 1,
 'ago': 1,
 '.\nHe': 2,
 'was': 3,
 'an': 1,
 'outlaw': 1,
 'friends': 1,
 'with': 1,
 'Pat': 3,
 'Garrett': 2,
 'who': 1,
 'a': 2,
 'lawman': 1,
 '.\nOne': 1,
 'day': 1,
 'had': 2,
 'to': 1,
 'bring': 1,
 '.\nBilly': 1,
 'would': 1,
 'not': 1,
 'come': 1,
 '.\nThey': 1,
 'gunfight': 1,
 'and': 1,
 'shot': 1,
 'his': 1,
 'friend': 1,
 '.\n': 1}

Eyeballing the count we see a number of words, including `"\nBilly"`,
which begin with `"\n"`.  This is because split(" ") is splitting only on space (as it was told to!) and not genereally handling
white space corectly (a newline character should be treated as white space too!).

So the rule with text is, if you're shooring for a list of words,
use `.split()` and not `.split(' ')`; `.split()` uses a soophisticated
regular expression definition of white space, and will almnost
always work better.

### 2.5  4 points

Write a **function** `find_word_forms` that takes a string `text_str` and a word `form` as its **two** arguments and returns all **words** in `text_str` that begin with `form`.
Write this without importing any Python modules.

Here are some tests that your function should pass:

```
>>> find_word_forms(sad_story, 'friend')
['friends', 'friend']
>>> find_word_forms("I'm singing in the rain", 'friend')
[]
>>> find_word_forms("I'm singing in the rain", 'in')
['in']
>>> find_word_forms("I'm singing in the rain", 'sing')
['singing']
>>> find_word_forms("I'm finding you fine", 'fin')
['finding', 'fine']
>>> find_word_forms(sad_story, 't')
['the', 'the', 'to', 'the']
```

Hint:  You may find it helpful to remember the
string method `startswith`.

In [12]:
def find_word_forms (text_str, form):
    return [wd for wd in text_str.split() if wd.startswith(form)]

In [11]:
def find_word_forms_2 (text_str, form):
    result = []
    for wd in text_str.split():
        if wd.startswith(form):
            result.append(wd)
    return result 

In [13]:
find_word_forms(sad_story, 't')

['the', 'the', 'to', 'the']

In [14]:
find_word_forms_2(sad_story, 't')

['the', 'the', 'to', 'the']

### 2.6   4 points

Write a function that converts degrees to radians. You are allowed
to use the following import statement:

```
from numpy import pi
```

The formula is

```
Radians = (Degrees/360) * 2 * pi
```

Here are some tests

```
>>> deg2rad(360)
6.283185307179586
>>> deg2rad(90)
1.5707963267948966
>>> deg2rad(72)
1.2566370614359172
```

In [1]:
from numpy import pi

def deg2rad (deg):
    return (deg/360) * 2 * pi

def deg2rad_equiv (deg):
    return (deg/180) * pi

scale_factor = pi/180

def deg2rad_more_efficient (deg):
    return deg * scale_factor

In [2]:
print(deg2rad(360))
print(deg2rad(90))
print(deg2rad(72))

6.283185307179586
1.5707963267948966
1.2566370614359172


In [3]:
print(deg2rad_more_efficient(360))
print(deg2rad_more_efficient(90))
print(deg2rad_more_efficient(72))

6.283185307179586
1.5707963267948966
1.2566370614359172


# Part 3 Numpy arrays 24 points

You must execute the next cell to do the problems in this section.

In [28]:
# Data cell

import numpy as np

xx = np.arange(0,43,3)

yy = xx.reshape((3,5))

In [116]:
xx

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42])

### 3.1  4 points

Write a single Python expression that returns 6 from `xx`

In [80]:
xx[2]

6

# 3.2

Write a single Python expression  that returns all members of `xx` divisible by 6.
Hint: Use a splice.

In [81]:
xx[::2]

array([ 0,  6, 12, 18, 24, 30, 36, 42])

In [17]:
xx[xx%6==0]

array([ 0,  6, 12, 18, 24, 30, 36, 42])

### 3.3  4 points

Write a single Python expression  that returns all members of `xx` greater than 18.
you may use a splice if you wish.

In [119]:
xx[7:]

array([21, 24, 27, 30, 33, 36, 39, 42])

### 3.4  4 points

Write a single Python expression  that returns the following
1D array from `yy`.

```
[15, 18, 21, 24, 27]
```

In [88]:
yy[1]

array([15, 18, 21, 24, 27])

Equivalently:

In [33]:
yy[1,:]

array([15, 18, 21, 24, 27])

Wrong:

In [29]:
yy[1:2]

array([[15, 18, 21, 24, 27]])

Notice the extra square brackets.  This is a 2D array:

In [30]:
yy[1:2].shape

(1, 5)

In [32]:
yy[1].shape

(5,)

### 3.5  4 points

Write a single Python expression  that returns the following
2D array from `yy`.

```
array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])
```

In [84]:
yy[:2]

array([[ 0,  3,  6,  9, 12],
       [15, 18, 21, 24, 27]])

### 3.6  4 points

Write a single Python expression  that returns the following
2D array from `yy`.

```
array([[21, 24],
       [36, 39]])
```

In [90]:
yy[1:3, 2:4]

array([[21, 24],
       [36, 39]])

# Part 4  Wine Data  24 points

In this exercise set, we load wine data. This is a multi class dataset that has data for three different wine types  (stored in `target` below) corresponding to three
different cultivators in a particular region of Italy.  These will just
be referred to as class_1 calss_2 and class_3 in the description below
and in the questions.
The chemical properties of the wine stored in the 2D numpy array `data` below are sufficient to identity the cultivator, but it's a challenging classification problem.

Wine recognition dataset
-----------------------------

**Data Set Characteristics:**

    :Number of Instances: 178
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
     
    The wine atributes listed in their column order.
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            10.6  30.0    19.5   3.3
    Magnesium:                    70.0 162.0    99.7  14.3
    Total Phenols:                0.98  3.88    2.29  0.63
    Flavanoids:                   0.34  5.08    2.03  1.00
    Nonflavanoid Phenols:         0.13  0.66    0.36  0.12
    Proanthocyanins:              0.41  3.58    1.59  0.57
    Colour Intensity:              1.3  13.0     5.1   2.3
    Hue:                          0.48  1.71    0.96  0.23
    OD280/OD315 of diluted wines: 1.27  4.00    2.61  0.71
    Proline:                       278  1680     746   315
    ============================= ==== ===== ======= =====

    :Missing Attribute Values: None
    :Class Distribution: class_0 (59), class_1 (71), class_2 (48)
    :Creator: R.A. Fisher
    :Donor: Michael Marshall (MARSHALL%PLU@io.arc.nasa.gov)
    :Date: July, 1988

This is a copy of UCI ML Wine recognition datasets.
https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data

The data is the results of a chemical analysis of wines grown in the same
region in Italy by three different cultivators. There are thirteen different
measurements taken for different constituents found in the three types of
wine.

Original Owners: 

Forina, M. et al, PARVUS - 
An Extendible Package for Data Exploration, Classification and Correlation. 
Institute of Pharmaceutical and Food Analysis and Technologies,
Via Brigata Salerno, 16147 Genoa, Italy.

Citation:

Lichman, M. (2013). UCI Machine Learning Repository
[https://archive.ics.uci.edu/ml]. Irvine, CA: University of California,
School of Information and Computer Science. 


You must evaluate the next cell to do the problems in this section.

In [34]:
from sklearn.datasets import load_wine
wdata = load_wine()
data = wdata.data
target = wdata.target

### 4.0 4 points 

Write a Python expression that returns s Boolean array defining
the set of rows of the `data` array with ash level less than 2.36  and flavinoids greater than 2.03.

In [37]:
B4_1 = (data[:,2] < 2.36) & (data[:,6] > 2.03)

Wont work

In [35]:
B4_1 = (data[:,2] < 2.36) and (data[:,6] > 2.03)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

A 1D array.

In [38]:
B4_1.shape

(178,)

Hence this is an error:

In [41]:
B4_1[:10,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [ ]:
Defining a set of rows:

In [40]:
B4_1[:10]

array([False,  True, False, False, False, False, False, False,  True,
        True])

### 4.1  5 points

Write a Python expression that returns the rows of the `data` array 
representing  wine samples with ash level less than 2.36  and flavinoids greater
than 2.03.  

JMG Our Boolean array can now be used as **mask** to return the set
of rows we want:

In [25]:
data[B4_1]

array([[1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.483e+01, 1.640e+00, 2.170e+00, 1.400e+01, 9.700e+01, 2.800e+00,
        2.980e+00, 2.900e-01, 1.980e+00, 5.200e+00, 1.080e+00, 2.850e+00,
        1.045e+03],
       [1.386e+01, 1.350e+00, 2.270e+00, 1.600e+01, 9.800e+01, 2.980e+00,
        3.150e+00, 2.200e-01, 1.850e+00, 7.220e+00, 1.010e+00, 3.550e+00,
        1.045e+03],
       [1.410e+01, 2.160e+00, 2.300e+00, 1.800e+01, 1.050e+02, 2.950e+00,
        3.320e+00, 2.200e-01, 2.380e+00, 5.750e+00, 1.250e+00, 3.170e+00,
        1.510e+03],
       [1.412e+01, 1.480e+00, 2.320e+00, 1.680e+01, 9.500e+01, 2.200e+00,
        2.430e+00, 2.600e-01, 1.570e+00, 5.000e+00, 1.170e+00, 2.820e+00,
        1.280e+03],
       [1.406e+01, 1.630e+00, 2.280e+00, 1.600e+01, 1.260e+02, 3.000e+00,
        3.170e+00, 2.400e-01, 2.100e+00, 5.650e+00, 1.090e+00, 3.710e+00,
        7.80

### 4.2 5 points

How many such rows are there?

In [26]:
B4_1.sum()

40

### 4.3  5 points

Write a Python expression that returns the rows of the `data` array 
representing wine samples such that they are not of class_1 and they
have  ash levels less than 2.36  and flavinoids greater than 2.03.

In [57]:
B4_3 = ~(target == 1) & B4_1
data[B4_3]

array([[1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.483e+01, 1.640e+00, 2.170e+00, 1.400e+01, 9.700e+01, 2.800e+00,
        2.980e+00, 2.900e-01, 1.980e+00, 5.200e+00, 1.080e+00, 2.850e+00,
        1.045e+03],
       [1.386e+01, 1.350e+00, 2.270e+00, 1.600e+01, 9.800e+01, 2.980e+00,
        3.150e+00, 2.200e-01, 1.850e+00, 7.220e+00, 1.010e+00, 3.550e+00,
        1.045e+03],
       [1.410e+01, 2.160e+00, 2.300e+00, 1.800e+01, 1.050e+02, 2.950e+00,
        3.320e+00, 2.200e-01, 2.380e+00, 5.750e+00, 1.250e+00, 3.170e+00,
        1.510e+03],
       [1.412e+01, 1.480e+00, 2.320e+00, 1.680e+01, 9.500e+01, 2.200e+00,
        2.430e+00, 2.600e-01, 1.570e+00, 5.000e+00, 1.170e+00, 2.820e+00,
        1.280e+03],
       [1.406e+01, 1.630e+00, 2.280e+00, 1.600e+01, 1.260e+02, 3.000e+00,
        3.170e+00, 2.400e-01, 2.100e+00, 5.650e+00, 1.090e+00, 3.710e+00,
        7.80

### 4.4 5 points

How many such rows are there?

In [30]:
B4_3.sum()

19

Alternative #2

In [ ]:
data[B4_3].shape[0]

Alternative #3

In [ ]:
len(data[B4_3])

#### wrong answer

In [58]:
data[B4_3].shape

(19, 13)

```
data[B4_3].shape
```

is not a computation of the number of rows of `a1` usable in further computations.   It returns a pairs of numbers. A correct answer must be an expression that returns a number, not a pair.  Hence, the following is a correct answer:

```
data[B4_3].shape[0]
```

This is exactly the number of rows.