## Numpy assignment solution

In [2]:
import numpy as np
x = np.array([2,3,1,0])
y =np.arange(10)
z = 2 + x

Write expressions in the next cell to retrieve 1 from `x`, 3 from `y`, and 3 from `z`.

In [6]:
x[2]
y[3]
z[2]

3

In the next cell, write an expression that generates a 5 by 5 array filled with zeros, and another  that generates a 1 by 1 array with a 1 in it.

In [8]:
five_by_five = np.zeros((5,5))
one_by_one = np.ones((1,1))

In [9]:
five_by_five

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
one_by_one

array([[ 1.]])

In [11]:
one_by_one == 1

array([[ True]], dtype=bool)

In [12]:
five_by_five == 0

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], dtype=bool)

In the next cell, write an expression that uses an assignment to a splice to make all the negative values in `a` be 0.  Attention: This can be done more easily in numpy than it can in normal Python.  See if you can do it the easy way.

In [17]:
a = np.arange(10,-1,-1) - 3

In [18]:
a

array([ 7,  6,  5,  4,  3,  2,  1,  0, -1, -2, -3])

There are two ways, the old way you learned with lists, and the new, which only works with arrays, and builds on the concept of elementwse operation.

In [21]:
a[-3:] = 0

In [16]:
a

array([7, 6, 5, 4, 3, 2, 1, 0, 0, 0, 0])

Here's the old way.

In [19]:
a[-3:] = [0,0,0]

In [20]:
a

array([7, 6, 5, 4, 3, 2, 1, 0, 0, 0, 0])

In the next cell write an expression that produces an array containing result of multiplying 7 by each of the first 12 integers (1 - 12). There's a hard way to do this and an easy way.  The easy way uses elementwise operations.

In [24]:
7 * np.arange(1,13)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84])

In [33]:
times_table = np.ones((12,12))
times_table

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [34]:
times_table = times_table * np.arange(1,13)
times_table

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
         12.],
       [  1.,   2.,  

In [35]:
times_table = times_table.transpose() * np.arange(1,13)

array([[   1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,    9.,
          10.,   11.,   12.],
       [   2.,    4.,    6.,    8.,   10.,   12.,   14.,   16.,   18.,
          20.,   22.,   24.],
       [   3.,    6.,    9.,   12.,   15.,   18.,   21.,   24.,   27.,
          30.,   33.,   36.],
       [   4.,    8.,   12.,   16.,   20.,   24.,   28.,   32.,   36.,
          40.,   44.,   48.],
       [   5.,   10.,   15.,   20.,   25.,   30.,   35.,   40.,   45.,
          50.,   55.,   60.],
       [   6.,   12.,   18.,   24.,   30.,   36.,   42.,   48.,   54.,
          60.,   66.,   72.],
       [   7.,   14.,   21.,   28.,   35.,   42.,   49.,   56.,   63.,
          70.,   77.,   84.],
       [   8.,   16.,   24.,   32.,   40.,   48.,   56.,   64.,   72.,
          80.,   88.,   96.],
       [   9.,   18.,   27.,   36.,   45.,   54.,   63.,   72.,   81.,
          90.,   99.,  108.],
       [  10.,   20.,   30.,   40.,   50.,   60.,   70.,   80.,   90.,
         100.,  110.

## Using your own data

Using your own data to make data frames sometimes requires a little preporcessing.  The basic
idea is to created a dictionary whose keys are column names and whose values
are the sequences of values for that column.  The trick is when you want to have an
index for columns, as is often necessary when you wanbt to show meaningful plots.  That has to be a predefined sequence of values as well.
The following example illustrates the idea.

## From [data science lab](http://datasciencelab.wordpress.com/2013/12/21/beautiful-plots-with-pandas-and-matplotlib/)

In [3]:
import pandas as pd
import matplotlib as mpl
from matplotlib.colors import LinearSegmentedColormap
from matplotlib.lines import Line2D
from matplotlib import pylab as plt
 
countries = ['France','Spain','Sweden','Germany','Finland','Poland','Italy',
             'United Kingdom','Romania','Greece','Bulgaria','Hungary',
             'Portugal','Austria','Czech Republic','Ireland','Lithuania','Latvia',
             'Croatia','Slovakia','Estonia','Denmark','Netherlands','Belgium']
extensions = [547030,504782,450295,357022,338145,312685,301340,243610,238391,
              131940,110879,93028,92090,83871,78867,70273,65300,64589,56594,
              49035,45228,43094,41543,30528]
populations = [63.8,47,9.55,81.8,5.42,38.3,61.1,63.2,21.3,11.4,7.35,
               9.93,10.7,8.44,10.6,4.63,3.28,2.23,4.38,5.49,1.34,5.61,
               16.8,10.8]
life_expectancies = [81.8,82.1,81.8,80.7,80.5,76.4,82.4,80.5,73.8,80.8,73.5,
                    74.6,79.9,81.1,77.7,80.7,72.1,72.2,77,75.4,74.4,79.4,81,80.5]
data = {'extension' : pd.Series(extensions, index=countries),
        'population' : pd.Series(populations, index=countries),
        'life expectancy' : pd.Series(life_expectancies, index=countries)}
 
df = pd.DataFrame(data)
df = df.sort('life expectancy')

In [15]:
fig, axes = plt.subplots(nrows=3, ncols=1)
col_axes = []
for i, c in enumerate(df.columns):
    col_axes.append(df[c].plot(kind='bar', ax=axes[i], figsize=(12, 10), title=c))
for axs in col_axes[:2]:
    labels = axs.get_xticklabels()
    for label in labels:
        label.set_rotation(40)
print fig.subplots_adjust(hspace=.6)
plt.show()

None
