$$\begin{array}[t]{lcr}
\mbox{Name}  &  \hspace{5in}\mbox{Numpy Quiz 2019}
\end{array}
$$

1)  Use the values defined in the code below for the next few problems.

In [2]:
import numpy as np
x = np.array([8,3,1,1,5])
y = np.arange(10)
z = 2 + x

In [4]:
x[4]

5

2)  Write an expression on the next line to retrieve 5 from `x`.

3)  Write an expression on the next line to retrieve 1 from `y`.

4)  Write an expression on the next line to retrieve 5 from `z`.

5)  On the next line, write an expression that generates a 3 by 5 array filled with zeros.

In [14]:
array_two[array_two[0] >= 90]

array([], shape=(0, 5), dtype=int64)

In [13]:
array_one > array_two

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [17]:
array_two[array_two >= 100]

array([175, 450])

In [20]:
array_one[:, array_one > 6]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [15]:
import numpy as np
array_one = \
np.array(
[[6,  3, 4, 1, 0],
[5,  2, 3, 2, 2],
[8,  3, 6, 2, 4],
[5,  1, 3, 1, 7],
[10, 4, 7, 2, 5]])

array_two = np.array([40, 175, 90, 450, 25])

6)  In the line below, write an expression that retrieves the second column of `array_one`.  Also write down the value returned by that expression.

7)  In the next cell, write an expression that retrieves the fourth row of `array_one`.

8)  In the next cell write an expression that retrieves the last two elements of the third column of `array_one`.

9)  In this cell,  write an expression that retrieves the following submatrix from `array_one`:

```
array([[6,2],
       [3,1]])
```

10)  In the next cell, write an expression that returns a Boolean array (every element is either `True` or `False`) that identifies the members of `array_two` which are greater than or equal to 100. 
Answers using a Python loop will not be accepted.

11) The code below defines two arrays.  The first array represents some data for a small set of individuals. It
represents their ages and income in thousands of dollars. The first column is age and the second is income.
The second array represents the clubs the same individuals belong to.  There are three possible clubs,
`0`, `1`, and `2`. So for example the 22 year-old individual with an income of 63.1K represented in the second row of `age_data` belongs to club `2`, because
`club[1]` is `2`.

In [21]:
import numpy as np
age_income_data = np.array([[47,57.2],
                            [22,63.1],
                            [14,88.1],
                            [20,97.5],
                            [31,32.1],
                            [28,110.3]])
club = np.array([0,2,1,0,1,2])

In [27]:
age_income_data[:,1]

array([ 57.2,  63.1,  88.1,  97.5,  32.1, 110.3])

In [28]:
age_income_data[age_income_data[:,0]<30]

array([[ 22. ,  63.1],
       [ 14. ,  88.1],
       [ 20. ,  97.5],
       [ 28. , 110.3]])

In the next line, write an expression that computes all the rows of `age_income_data` representing
individuals whose club is `2`.   Use a Boolean mask.  Answers not using a Boolean mask will receive no credit.

12)  In the next cell, write a line of code that computes all the rows of `age_income_data` representing
individuals whose income is over 80,000.  Use a Boolean mask.  Answers not using a Boolean mask will receive no credit.

13. The code below defines an array that contains some data for a small set of individuals. It represents their ages and whether they own a home. The first column is age and the second is home ownership. The second array represents the clubs the same individuals belong to. A value of 0 in the home ownership column means the individual reprsented by that  row does not own a home; a value of 1 means they do own a home. . So for example the 22 year-old individual represented in the second row of age_home_ownership owns a home  because the value in the 2nd column in the second row  is 1.

In [37]:
age_home_ownership = np.array([[47, 1],
                               [22, 1],
                               [14, 1],
                               [20, 0],
                               [31, 1],
                               [28, 0]])

In [39]:
age_home_ownership[age_home_ownership[:,1]]

array([[22,  1],
       [22,  1],
       [22,  1],
       [47,  1],
       [22,  1],
       [47,  1]])

In [43]:
X = np.array((4,1,2,4,8))
Y = X[::-1]
Z= np.array((8,3,1,2,4))
X+Y

array([12,  5,  4,  5, 12])

In [49]:
2 * np.arange(24).reshape((4,6))

array([[ 0,  2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20, 22],
       [24, 26, 28, 30, 32, 34],
       [36, 38, 40, 42, 44, 46]])

In [48]:
np.arange(2,26).reshape((4,6))

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25]])

In [51]:
2 * np.arange(1,25).reshape((4,6))

array([[ 2,  4,  6,  8, 10, 12],
       [14, 16, 18, 20, 22, 24],
       [26, 28, 30, 32, 34, 36],
       [38, 40, 42, 44, 46, 48]])

In [44]:
X * Z

array([32,  3,  2,  8, 32])