## Numpy Times table example

Suppose you want to create a times-table. Here's how you do it with a loop:

In [25]:
import numpy as np
times_table = np.ones((12,12),dtype=int)
for a in range(1,13):
    for b in range(1,13):
        times_table[a-1,b-1] = a*b
times_table

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

Let's look at how to do much more efficiently this using array operations, using the mathematical regularity
of the structure we're trying to build to help us.

We're going to use broadcaasting to get it done.
Recall that `numpy` uses elementwise operations to interpret the following.

In [24]:
7 * np.arange(1,13)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84])

This of of course is row 7 of our goal, a times table.  The idea is to do some thing
like this to a 2D array.  Here's how.

In [3]:
ones_12x12 = np.ones((12,12),dtype=int)
ones_12x12

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In the next example, broadcasting naturally applies muliplication of the array on the right to each
of the **rows** of the array on the left.  

In [34]:
times_table = ones_12x12 * np.arange(1,13)
print(times_table)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
 [ 1  2  3  4  5  6  7  8  9 10 11 12]]


We now have a table with 1's in the first column, 2's in  the second, and so on.
Transpose this and we have

In [35]:
times_table.T

array([[ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4],
       [ 5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5],
       [ 6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6],
       [ 7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7],
       [ 8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8],
       [ 9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11],
       [12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]])

Apply row-wise multiplication of 1-13 again, and we have a times table, created without any loops.

In [36]:
times_table.T * np.arange(1,13)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

Let's do it all in one step:

In [33]:
(np.ones((12,12),dtype=int) * np.arange(1,13)).T * np.arange(1,13)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

### Broadcast in different dimensions

Here we use our times table example to try to clarify the distinction between row-wise
and column-wise broadcasting.  In the process, describe an alternative way of building the times table that is arguably conceptually simpler.

Broadcasting a 1D array  to match a 2D array always works in a **row-wise** direction.  The general rule is, the 1D array has to match the last dimension of the 2D array:
(12,) can broadcast to match (12,12) or (11,12) but not (12,11).

In [51]:
np.ones((11,12)) * np.arange(1,13) 

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
       [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [50]:
 np.ones((12,11)) * np.arange(1,13) 

ValueError: operands could not be broadcast together with shapes (12,) (12,11) 

Consider the version that worked.  To get 

```
ones_11x12 * np.arange(1,13)
```

to work. we broadcast the 1D vector

```
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
```

into a 2D vector each of whose **rows** is a copy of
the 1D vector.

```
array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
```
This has the shape we want, 11x12, enabling 
us to do do element-wise multiplication with the 11x12 ones matrix.

In the case of the 12x11 matrix, broadcasting to the shape 11x12 is of 
no use, so this is where we want columnwise broadcasting. That is done by reshaping the 1D 
vector of shape (12,) into a 2D vector of shape (12,1)

```
>>>> col_vec = np.arange(1,13).reshape(12,-1)
>>> col_vec
array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])
```

And a 12x1 2D array **can** be broadcast to a 12x11 shape.  In general with 2D arrays,
if there is a dimension of size 1, broadcasting can happen along that dimension.
So 

```
MxN * Mx1
MxN * 1xN
MxN * 1x1
```

all work.  And of course the last is just multiplkicaytion be a scalar.

Demonstrating.

In [52]:
col_vec = np.arange(1,13).reshape(12,-1)
ones_12x11 = np.ones((12,11))
ones_12x11 * col_vec

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [11., 11., 11., 11., 11., 11., 11., 11., 11., 11., 11.],
       [12., 12., 12., 12., 12., 12., 12., 12., 12., 12., 12.]])


We now have a matrix in which each column is
the range(1,13).To get our times table, we  
multiply this by the 1D range vector; rowwise
broadcasting gives us the result we want.

In [44]:
ones_12x12 * np.arange(1,13).reshape(12,-1)
col_vec = np.arange(1,13).reshape(12,-1);  print(col_vec.shape)
ones_12x12 * col_vec *  np.arange(1,13)

(12, 1)


array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70,  77,  84],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80,  88,  96],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90,  99, 108],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [ 11,  22,  33,  44,  55,  66,  77,  88,  99, 110, 121, 132],
       [ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120, 132, 144]])

### Example

Convert to  percentages: 
Each cell reports the percentage of a column's total count
represented by that cell's count.

First sum the columns; then divide by the column totals.

In [45]:
import numpy as np
a = np.arange(24)
a2d = a.reshape((4,6))
print('a2d: ')
print(a2d)
col_sums = a2d.sum(axis=0)
print()
print('col sums: ')
print(col_sums)


a2d: 
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

col sums: 
[36 40 44 48 52 56]


Now try to divide each row by  col_sums.

That is, do the equivalent of what the following for-loop does, but without
a for-loop.

In [72]:
col_percentages[0,:] / col_sums

array([0.        , 0.025     , 0.04545455, 0.0625    , 0.07692308,
       0.08928571])

In [82]:
np.array([a2d[i,:]/col_sums for i in range(rows)]).shape

(4, 6)

In [74]:
(rows,cols) = a2d.shape
col_percentages = np.zeros((rows,cols))

# Divide each row by col sums
for i in range(rows):
    col_percentages[i,:] = a2d[i,:]/col_sums
col_percentages

array([[0.        , 0.025     , 0.04545455, 0.0625    , 0.07692308,
        0.08928571],
       [0.16666667, 0.175     , 0.18181818, 0.1875    , 0.19230769,
        0.19642857],
       [0.33333333, 0.325     , 0.31818182, 0.3125    , 0.30769231,
        0.30357143],
       [0.5       , 0.475     , 0.45454545, 0.4375    , 0.42307692,
        0.41071429]])

This can be done easily because the 1D col_sums 
vector computed in the last cell will broadcast rowwise.

Write the answer to this easy problem in the cell below.
The correct answer is a few cells below.

In [64]:

print(f'{a2d.shape} divided by {col_sums.shape}')

col_percentages = a2d/col_sums
col_percentages

(4, 6) divided by (6,)


array([[0.        , 0.025     , 0.04545455, 0.0625    , 0.07692308,
        0.08928571],
       [0.16666667, 0.175     , 0.18181818, 0.1875    , 0.19230769,
        0.19642857],
       [0.33333333, 0.325     , 0.31818182, 0.3125    , 0.30769231,
        0.30357143],
       [0.5       , 0.475     , 0.45454545, 0.4375    , 0.42307692,
        0.41071429]])

Confirm that these are indeed percentages by summing the cols of `percentages`.

In [75]:
col_percentages.sum(axis=0)

array([1., 1., 1., 1., 1., 1.])

Now the more challenging problem.  The following cell computes
row sums for the 4 rows of `a2d`.  Use that row
sum vector to produce a 2d array `row_percentages` in which each cell represents
the percentage of a **row's** total count represented by that cell's count.

In [57]:
row_sums = a2d.sum(axis=1)
row_sums

array([ 15,  51,  87, 123])

So if we wrote a  for loop to compute `row_percentages`
it would be:

In [61]:
(rows,cols) = a2d.shape

row_percentages = np.zeros((rows,cols))
for i in range(cols):
        row_percentages[:,i] = a2d[:,i]/row_sums
row_percentages

array([[0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
        0.33333333],
       [0.11764706, 0.1372549 , 0.15686275, 0.17647059, 0.19607843,
        0.21568627],
       [0.13793103, 0.14942529, 0.16091954, 0.17241379, 0.18390805,
        0.1954023 ],
       [0.14634146, 0.15447154, 0.16260163, 0.17073171, 0.17886179,
        0.18699187]])

Your next challenge:
Define `row_percentages` a different (more efficient way),
through a single array/by array division.

Confirm the correctness of your answer by showing each row
of `row_percentages` sums to 1.

In [66]:
# (4,6) divided by (4,1)
print(f'{a2d.shape} divided by {row_sums[:,np.newaxis].shape}')
row_percentages = a2d/row_sums[:,np.newaxis]
row_percentages

(4, 6) divided by (4, 1)


array([[0.        , 0.06666667, 0.13333333, 0.2       , 0.26666667,
        0.33333333],
       [0.11764706, 0.1372549 , 0.15686275, 0.17647059, 0.19607843,
        0.21568627],
       [0.13793103, 0.14942529, 0.16091954, 0.17241379, 0.18390805,
        0.1954023 ],
       [0.14634146, 0.15447154, 0.16260163, 0.17073171, 0.17886179,
        0.18699187]])

In [67]:
row_percentages.sum(axis=1)

array([1., 1., 1., 1.])

### Timing results

Array computing is tricky, and efficiency issues don't always work out the way you think they will.

Even the most experienced programmers know that they best evidence is to try it, so below we try, and find
a speedup factor of a little less than 6 using broadcasting and array operations.  As always, mileage may vary on your individual machines.  

In [13]:
import timeit
import numpy as np

py_secs = timeit.timeit("""for a in range(1,13): 
                            for b in range(1,13): 
                              times_table[a-1,b-1] = a*b""",
                        setup="import numpy as np;times_table = np.ones((12,12),dtype=int)",                        
                        number=100_000)

array_secs = timeit.timeit('times_table * np.arange(1,13).T * np.arange(1,13)',
                            setup="import numpy as np;times_table = np.ones((12,12),dtype=int)",
                            number=100_000)

array_secs2 = timeit.timeit("""col_vec = np.arange(1,13).reshape(12,-1); 
ones_12x12 * col_vec * np.arange(1,13)""",
                            setup="import numpy as np;ones_12x12 = np.ones((12,12),dtype=int)",
                            number = 100_000)

#array_secs2 = timeit.timeit("""col_vec = np.arange(1,13).reshape(12,-1); 
#ones_12x12 * col_vec * np.arange(1,13)""",
#                            setup="import numpy as np;ones_12x12 = np.ones((12,12),dtype=int)",
#                            number = 100_000)

print ("Normal Python: {0:.3f} sec".format(py_secs))

print("NumPy: {0:.3f} sec".format(array_secs))

print("NumPy: {0:.3f} sec".format(array_secs2))


Normal Python: 2.660 sec
NumPy: 0.386 sec
NumPy: 0.420 sec
