Name:

Red ID:

## Numpy Quiz 2016

Use the values defined in the code below for the next few problems.

In [1]:
import numpy as np
x = np.array([8,3,1,1,5])
y =np.arange(10)
z = 2 + x

Write an expression on the next line to retrieve 5 from `x`.

In [2]:
x[-1]

5

Write an expression on the next line to retrieve 1 from `y`.

In [3]:
y[1]

1

Write an expression on the next line to retrieve 5 from `z`.

In [4]:
z[1]

5

On the next line, write an expression that generates a 3 by 5 array filled with zeros.

In [5]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

<style>
    @font-face {
        font-family: "Computer Modern";
        src: url('http://mirrors.ctan.org/fonts/cm-unicode/fonts/otf/cmunss.otf');
    }
    div.cell{
        width:800px;
        margin-left:16% !important;
        margin-right:auto;
    }
    h1 {
        font-family: Helvetica, serif;
    }
    h4{
        margin-top:12px;
        margin-bottom: 3px;
       }
    div.text_cell_render{
        font-family: Computer Modern, "Helvetica Neue", Arial, Helvetica, Geneva, sans-serif;
        line-height: 145%;
        font-size: 130%;
        width:800px;
        margin-left:auto;
        margin-right:auto;
    }
    .CodeMirror{
            font-family: "Source Code Pro", source-code-pro,Consolas, monospace;
    }
    .text_cell_render h5 {
        font-weight: 300;
        font-size: 22pt;
        color: #4057A1;
        font-style: italic;
        margin-bottom: .5em;
        margin-top: 0.5em;
        display: block;
    }
    
    .warning{
        color: rgb( 240, 20, 20 )
        }  

In [6]:
import numpy as np
array_one = \
np.array(
[[6,  3, 4, 1],
[5,  2, 3, 2],
[8,  3, 6, 2],
[5,  1, 3, 1],
[10, 4, 7, 2]])

array_two = np.array([40, 175, 90, 450])

In the line below, write an expression that retrieves the second column of `array_one`.  Also write down the value returned by that expression.

In [7]:
array_one[:,1]

array([3, 2, 3, 1, 4])

In the next cell, write an expression that retrieves the third row of `array_one`.

In [8]:
array_one[2,:]

array([8, 3, 6, 2])

In the next cell write an expression that retrieves the first two elements of the third column of `array_one`.

In [9]:
array_one[2,0:2]

array([8, 3])

In the next cell write an expression that retrieves the following submatrix from `array_one:

```
array([[3,1],
       [7,2]])
```

In [10]:
array_one[3:5,2:4]

array([[3, 1],
       [7, 2]])

In the next cell, write an expression that returns a Boolean array (every element is either `True` or `False`) that identifies the members of `array_two` which are greater than or equal to 100.

In [10]:
array_two >= 100

NameError: name 'array_two' is not defined

## Boolean indexing

The code below defines two arrays.  The first array represents some data for a small set of individuals. It
represents their ages and income in thousands of dollars. The first column is age and the second is income.
The second array represents the clubs the same individuals belong to.  There are three possible clubs,
0, 1, AND 2. So for example the individual represented in the second row of `age_data` belongs to club `1`, because
`club[1]` is `1`.

In [17]:
print age_income_data
print age_income_data[:,:]
print age_income_data [0:3,:]
print age_income_data [[1,3,4],:]

[[  47.    57.2]
 [  22.    63.1]
 [  14.    88.1]
 [  20.    97.5]
 [  39.    56.8]
 [  35.    22.4]
 [  31.    32.1]
 [  28.   110.3]]
[[  47.    57.2]
 [  22.    63.1]
 [  14.    88.1]
 [  20.    97.5]
 [  39.    56.8]
 [  35.    22.4]
 [  31.    32.1]
 [  28.   110.3]]
[[ 47.   57.2]
 [ 22.   63.1]
 [ 14.   88.1]]
[[ 22.   63.1]
 [ 20.   97.5]
 [ 39.   56.8]]


In [12]:
import numpy as np
age_income_data = np.array([[47,57.2],[22,63.1],[14,88.1],[20,97.5],[39,56.8],[35,22.4],[31,32.1],[28,110.3]])
club = np.array([0,1,0,1,0,0,2,2])

Here is what the `age_income_data` looks like:

In [14]:
age_income_data

array([[  47. ,   57.2],
       [  22. ,   63.1],
       [  14. ,   88.1],
       [  20. ,   97.5],
       [  39. ,   56.8],
       [  35. ,   22.4],
       [  31. ,   32.1],
       [  28. ,  110.3]])

In the next line, write an expression that computes all the rows of `age_income_data` representing individuals whose club is `0`.   Hint: Construct a Boolean array, then use that array.  

In [14]:
print club == 0
print age_income_data[club==0,]

[ True False  True False  True  True False False]
[[ 47.   57.2]
 [ 14.   88.1]
 [ 39.   56.8]
 [ 35.   22.4]]


In the next cell, write a line of code that computes all the rows of `age_income_data` representing individuals whose age is over 30. Hint:  We need a Boolean array that just finds the rows whose first column is over 30.
Then we use that to index the rows of `age_income_data`.

In [7]:
print age_income_data
print age_income_data[:,0] > 30
print age_income_data[age_income_data[:,0] > 30,:]

[[  47.    57.2]
 [  22.    63.1]
 [  14.    88.1]
 [  20.    97.5]
 [  39.    56.8]
 [  35.    22.4]
 [  31.    32.1]
 [  28.   110.3]]
[ True False False False  True  True  True False]
[[ 47.   57.2]
 [ 39.   56.8]
 [ 35.   22.4]
 [ 31.   32.1]]


Note that the following idea doesn't work.  It returns a 1D array with all the numbers in `age_income_data` that are over 30.  That's not what we want.  Make sure you understand why.

In [9]:
print age_income_data
print age_income_data > 30
print age_income_data[age_income_data > 30]

[[  47.    57.2]
 [  22.    63.1]
 [  14.    88.1]
 [  20.    97.5]
 [  39.    56.8]
 [  35.    22.4]
 [  31.    32.1]
 [  28.   110.3]]
[[ True  True]
 [False  True]
 [False  True]
 [False  True]
 [ True  True]
 [ True False]
 [ True  True]
 [False  True]]
[  47.    57.2   63.1   88.1   97.5   39.    56.8   35.    31.    32.1
  110.3]


In [ ]:
print age_income_data
print age_income_data > 30
print age_income_data[age_income_data > 30]