Name:

Red ID:

## Numpy Quiz 2016

Use the values defined in the code below for the next few problems.

In [1]:
import numpy as np
x = np.array([8,3,1,1,5])
y =np.arange(10)
z = 2 + x

Write an expression on the next line to retrieve 5 from `x`.

Write an expression on the next line to retrieve 1 from `y`.

Write an expression on the next line to retrieve 5 from `z`.

On the next line, write an expression that generates a 3 by 5 array filled with zeros.

<style>
    @font-face {
        font-family: "Computer Modern";
        src: url('http://mirrors.ctan.org/fonts/cm-unicode/fonts/otf/cmunss.otf');
    }
    div.cell{
        width:800px;
        margin-left:16% !important;
        margin-right:auto;
    }
    h1 {
        font-family: Helvetica, serif;
    }
    h4{
        margin-top:12px;
        margin-bottom: 3px;
       }
    div.text_cell_render{
        font-family: Computer Modern, "Helvetica Neue", Arial, Helvetica, Geneva, sans-serif;
        line-height: 145%;
        font-size: 130%;
        width:800px;
        margin-left:auto;
        margin-right:auto;
    }
    .CodeMirror{
            font-family: "Source Code Pro", source-code-pro,Consolas, monospace;
    }
    .text_cell_render h5 {
        font-weight: 300;
        font-size: 22pt;
        color: #4057A1;
        font-style: italic;
        margin-bottom: .5em;
        margin-top: 0.5em;
        display: block;
    }
    
    .warning{
        color: rgb( 240, 20, 20 )
        }  

In [2]:
import numpy as np
array_one = \
np.array(
[[6,  3, 4, 1],
[5,  2, 3, 2],
[8,  3, 6, 2],
[5,  1, 3, 1],
[10, 4, 7, 2]])

array_two = np.array([40, 175, 90, 450])

In the line below, write an expression that retrieves the second column of `array_one`.  Also write down the value returned by that expression.

In the next cell, write an expression that retrieves the third row of `array_one`.

In the next cell write an expression that retrieves the first two elements of the third column of `array_one`.

In the next cell write an expression that retrieves the following submatrix from `array_one:

```
array([[3,1],
       [7,2]])
```

In the next cell, write an expression that returns a Boolean array (ever element is either `True` or `False`) that identifies the members of `matrix_two` which are greater than or equal to 100.

## Boolean indexing

The code below defines two arrays.  The first array represents some data for a small set of individuals. It
represents their ages and income in thousands of dollars. The first column is age and the second is income.
The second array represents the clubs the same individuals belong to.  There are three possible clubs,
0, 1, AND 2. So for example the individual represented in the second row of `age_data` belongs to club `1`, because
`club[1]` is `1`.

In [1]:
import numpy as np
age_income_data = np.array([[47,57.2],[22,63.1],[14,88.1],[20,97.5],[39,56.8],[35,22.4],[31,32.1],[28,110.3]])
club = np.array([0,1,0,1,0,0,2,2])

Here is what the `age_income_data` looks like:

In [9]:
age_income_data

array([[  47. ,   57.2],
       [  22. ,   63.1],
       [  14. ,   88.1],
       [  20. ,   97.5],
       [  39. ,   56.8],
       [  35. ,   22.4],
       [  31. ,   32.1],
       [  28. ,  110.3]])

In the next line, write an expression that computes all the rows of `age_income_data` representing
individuals whose club is `0`.   Use a Boolean mask.

In [4]:
age_income_data[club==0]

array([[47. , 57.2],
       [14. , 88.1],
       [39. , 56.8],
       [35. , 22.4]])

In the next cell, write a line of code that computes all the rows of `age_income_data` representing
individuals whose age is over 30.  Use a Boolean mask.